### ISSUE TITLE
Built application does not take arguments

### ISSUE THREAD

**Issue by uranusjr** [indygreg/PyOxidizer#10]
I think so? I plan to work on this, and try to ease myself into the code base at the same time.

**Comment by indygreg** [comment]
Can you provide more details? It's quite possible we need to add a call to `PySys_SetArgv()` or `PySys_SetArgvEx()`.

That being said, that API wants a `wchar_t` and getting that from Rust may be more trouble than its worth. The implementation of the function simply constructs a `PyList` with `str` entries representing the arguments and then sets `sys.argv` to that list. So I would implement this manually, without going through `PySys_SetArgv()`. Keep in mind that on Windows, the arguments are already encoded whereas on POSIX, they are bytes.
