### ISSUE TITLE
SyntaxError: invalid character in identifier when compiling python source with comment

### ISSUE THREAD

**Issue by bsiegel** [indygreg/PyOxidizer#13]
**Environment:**
MacOS 10.14.5
Rust 1.35
Pyoxidizer built from master (b62fdb7) as of ~3pm PT 6/24/19

**Issue:**
It looks like bytecode-compiler is bailing out trying to compile a source file with comments. Specifically I get this error trying to package the `azure-cli` pip package:

```
Traceback (most recent call last):
  File "/var/folders/g9/828fv6h94kdf0_c9s91d75g80000gn/T/bytecode-compiler.xEe9iQHo3GOW/bytecodecompiler.py", line 59, in <module>
    code = compile(source, name, 'exec', optimize=optimize_level)
  File "adal", line 1
    #------------------------------------------------------------------------------
    ^
SyntaxError: invalid character in identifier
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Empty }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: pyoxidizer::pyrepackager::bytecode::BytecodeCompiler::compile
  10: pyoxidizer::pyrepackager::repackage::resolve_python_resources
  11: pyoxidizer::pyrepackager::repackage::process_config
  12: pyoxidizer::projectmgmt::build_pyoxidizer_artifacts
  13: pyoxidizer::projectmgmt::build_project
  14: pyoxidizer::projectmgmt::build
  15: pyoxidizer::cli::run_cli
  16: pyoxidizer::main
  17: std::rt::lang_start::{{closure}}
  18: std::panicking::try::do_call
  19: __rust_maybe_catch_panic
  20: std::rt::lang_start_internal
  21: main
```

`azure-cli` depends on `adal`, and this looks like the line in that library where it's bailing out: https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/adal/__init__.py#L1

The configuration is fairly simple, all I changed from the default template was:
```toml
[[packaging_rule]]
type = "pip-install-simple"
package = "azure-cli"

[[embedded_python_run]]
mode = "module"
module = "azure-cli"
```

**Comment by bsiegel** [comment]
Update, I tried a minimal repro of this and it still fails.

1. `pyoxidizer init adal`
2. Add the following to the generated pyoxidizer.toml (I put mine on L96):
    ```toml
    [[packaging_rule]]
    type = "pip-install-simple"
    package = "adal"
    ```

3. `pyoxidizer build`

The result is the same failure in bytecode-compiler as above.

**Comment by indygreg** [comment]
This particular file has a BOM (`ef bb bf`), which something doesn't like.

For context, what's happening under the hood is `pyoxidizer` is opening a Python process to be used for compiling Python bytecode. It sends source over a pipe to the Python process. The Python process needs to decode `bytes` to a `str`. The logic that Python uses to convert the bytes in source (normally backed by a file) to a `str` is somewhat complicated and it is likely that the Python code I wrote to do this is incomplete.

This is definitely a bug in PyOxidizer. Thank you for filing it!

**Comment by indygreg** [comment]
Please try running PyOxidizer from the Git `master` branch and let me know if the issue isn't fixed for you. See https://pyoxidizer.readthedocs.io/en/latest/getting_started.html#installing for how to do that.

**Comment by bsiegel** [comment]
Hey Greg, I'm still hitting this here with the minimal repro. I think there's a bug in your fix for the issue here:
https://github.com/indygreg/PyOxidizer/blob/c610984ac60ed818f78e10942001374fabb5f41c/pyoxidizer/src/pyrepackager/bytecodecompiler.py#L61

I believe this should be `source = source[3:]`

As is, bytecode compiler is removing one too many characters, causing it to bail out with "SyntaxError: invalid syntax" because the `#` start of the comment was removed.

**Comment by indygreg** [comment]
I can't believe I made that off-by-1 error!

I just committed a fix. Please try again! Sorry for the confusion.

**Comment by bsiegel** [comment]
👍 looks fixed now!
