### ISSUE TITLE
Allow PyOxidizer to filter-exclude arbitrary paths

### ISSUE THREAD

**Issue by bsiegel** [indygreg/PyOxidizer#135]
I've been trying to use PyOxidizer on a Python project that uses the [PyInvoke](https://github.com/pyinvoke/invoke) library. This library is Python2 and Python3 compatible and it does this by vendoring both a Python 2 and a Python 3 version of PyYAML (under `invoke/vendor/yaml{2,3}`). This is causing PyOxidizer to bail out when it tries to run bytecodecompiler on the Python2 source code:

```
Traceback (most recent call last):
  File "/var/folders/g9/828fv6h94kdf0_c9s91d75g80000gn/T/bytecode-compiler.MsDXvFD0omNs/bytecodecompiler.py", line 65, in <module>
    code = compile(source, name, 'exec', optimize=optimize_level)
  File "invoke.vendor.yaml2.constructor", line 130
    except TypeError, exc:
                    ^
SyntaxError: invalid syntax
```

I think I could get around this if I was able to specify `invoke/vendor/yaml2` as an excluded path during the filtering phase since the Python2 code would never be executed.

**Comment by indygreg** [comment]
This is a reasonable feature request.

**Comment by jayvdb** [comment]
Similar underlying problem as https://github.com/indygreg/PyOxidizer/issues/147

@bsiegel , have you tried using the PackageRoot or Virtualenv packaging rules?
i.e. you do the install manually into the venv, and then the PackageRoot or Virtualenv packaging rule picks up the installed packages from there.

Is this Python project that uses the PyInvoke library open source / available somewhere?

Is it critical for the PyYAML LibYAML-based fast helper to be used?  I found it a bit finicky to install, but thankfully it is optional, and the PyYAML pure python library is fully functional.

**Comment by bsiegel** [comment]
I have tried the Virtualenv packaging rule, though I hadn't considered just mucking about inside the virtualenv and deleting the unnecessary Python2 files. That would probably work, but is a little ugly to automate.

Yes, the project I was working to PyOxidize was https://github.com/Azure/azure-cli - however you should definitely be able to repro this with any project that uses PyInvoke, since it is PyInvoke that is vendoring the Python2 version of PyYAML.

I would assume that the LibYAML helper is not required, but the compilation seemed to work successfully for the vendored Python3 version of PyYAML even without making any changes to disable the compilation / use of the LibYAML helper.

**Comment by indygreg** [comment]
PyOxidizer 0.8 introduced a feature that allows you to register Starlark function callbacks that can be used to influence how resources are added. Using a callback function, you can set the `.add_include` attribute to false to prevent a particular resource from being added.

See https://pyoxidizer.readthedocs.io/en/stable/pyoxidizer_config_resource_add_attributes.html and https://pyoxidizer.readthedocs.io/en/stable/pyoxidizer_packaging_resources.html for documentation of this feature.

This functionality is generic and can be made to be arbitrarily complex via Starlark code. As such, I believe it fulfills the feature request in this issue, so I'm marking this issue as closed.
