### ISSUE TITLE
pyoxidizer run fails behind proxy

### ISSUE THREAD

**Issue by jteiwes** [indygreg/PyOxidizer#15]
When running the [getting started example](https://pyoxidizer.readthedocs.io/en/latest/getting_started.html#getting-started) the call to `pyoxidizer run` fails when downloading the python environment from behind a proxy. I am using windows cmd, the proxy settings are correctly set in the environment and working for e.g. cargo or wget:

> ~/pyapp> SET HTTPS_PROXY="http://user:pass@proxy_ip:proxy_port"
> ~/pyapp> SET HTTP_PROXY="http://user:pass@proxy_ip:proxy_port"
> ~/pyapp> pyoxidizer.exe run
> no existing PyOxidizer artifacts found
> processing config file ~/pyapp\pyoxidizer.toml
> resolving Python distribution...
> downloading https://github.com/indygreg/python-build-standalone/releases/download/20190617/cpython-3.7.3-windows-amd64-20190618T0516.tar.zst
> thread 'main' panicked at 'unable to perform HTTP request: Error(Hyper(Error(Connect, Os { > code: 11001, kind: Other, message: "Der angegebene Host ist unbekannt." })), "https://github.com/indygreg/python-build-standalone/releases/download/20190617/cpython-3.7.3-windows-amd64-20190618T0516.tar.zst")', src\libcore\result.rs:997:5
> note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> ~/pyapp>

Is there a way, to set the proxy login info into the pyoxidizer.toml config file? So far i did not find any info on this..

**Comment by indygreg** [comment]
Thank you for the valid bug report!

I would have expected the Rust crate we're using (`reqwest`) to automatically handle the environment variables, as many HTTP libraries do that automatically. But it appears it doesn't.

Until I have time to fix this (hopefully in ~10 hours), you can work around the problem by downloading the archives referenced in the `pyoxidizer.toml` file and then changing the `url` line in the `pyoxidizer.toml` to `local_path` and point to the downloaded file. Since I see you are using Windows, remember to escape path components `\` with `\\` in the TOML string or convert path `\` characters to `/`.

**Comment by jteiwes** [comment]
> work around the problem by downloading the archives referenced in the `pyoxidizer.toml` file and then changing the `url` line in the `pyoxidizer.toml` to `local_path` and point to the downloaded file

This is exactly what i did :-)

**Comment by indygreg** [comment]
This should be fixed in `master`. Please reopen if it doesn't work as expected.

**Comment by glandium** [comment]
It feels like reqwest should at least have a helper for this. Did you open an issue?

**Comment by indygreg** [comment]
It seems like https://github.com/seanmonstar/reqwest/pull/547 implements the feature in `reqwest`.

**Comment by HarpPDX** [comment]
@indygreg 
'pyoxidizer build' failing -- using PyOxidizer 0.3.0 on Linux behind corporate firewall/proxy.  http_proxy and https_proxy environment variables are set.

```
~$ pyoxidizer init pyoxtst
     Created binary (application) package
creating pyoxtst/pyembed
creating pyoxtst/pyembed/src
writing pyoxtst/pyembed/src/config.rs
writing pyoxtst/pyembed/src/data.rs
writing pyoxtst/pyembed/src/importer.rs
writing pyoxtst/pyembed/src/lib.rs
writing pyoxtst/pyembed/src/osutils.rs
writing pyoxtst/pyembed/src/pyalloc.rs
writing pyoxtst/pyembed/src/pyinterp.rs
writing pyoxtst/pyembed/src/pystr.rs
writing pyoxtst/pyembed/Cargo.toml
writing pyoxtst/pyembed/build.rs
writing pyoxtst/src/main.rs
writing pyoxtst/pyoxidizer.toml

A new Rust binary application has been created in pyoxtst

This application can be built by doing the following:

  $ cd pyoxtst
  $ pyoxidizer build
  $ pyoxidizer run

The default configuration is to invoke a Python REPL. You can
edit the various pyoxidizer.*.toml config files or the main.rs
file to change behavior. The application will need to be rebuilt
for configuration changes to take effect.
~$ cd pyoxtst
~/pyoxtst$ pyoxidizer build
no existing PyOxidizer artifacts found
processing config file /home/redacted/pyoxtst/pyoxidizer.toml
resolving Python distribution...
downloading https://github.com/indygreg/python-build-standalone/releases/download/20190816/cpython-3.7.4-linux64-20190817T0224.tar.zst
thread 'main' panicked at 'unable to perform HTTP request: Error(Hyper(Error(Connect, Custom { kind: Other, error: Ssl(Error { code: ErrorCode(5), cause: None }, X509VerifyResult { code: 0, error: "ok" }) })), "https://github.com/indygreg/python-build-standalone/releases/download/20190816/cpython-3.7.4-linux64-20190817T0224.tar.zst")', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
~/pyoxtst$ pyoxidizer --version
PyOxidizer 0.3.0
~/pyoxtst$ env | grep _proxy
https_proxy=https://proxy.redacted.com:912
http_proxy=http://proxy.redacted.com:911

```
