### ISSUE TITLE
Unnecessary touching of pyoxidizer.toml

### ISSUE THREAD

**Issue by jayvdb** [indygreg/PyOxidizer#156]
`pyoxidizer.toml` is rewritten to disk even when nothing has changed from the toml that was loaded.

**Comment by indygreg** [comment]
Yeah, we could probably make this a no-op if the file contents don't change. That could be useful for build systems that take mtimes into account.

**Comment by indygreg** [comment]
PyOxidizer no longer has TOML configuration files. So I'm going to close this issue.
