### ISSUE TITLE
undefined symbol: _PyEval_RequestCodeExtraIndex

### ISSUE THREAD

**Issue by jayvdb** [indygreg/PyOxidizer#157]
Running the CPython test suite, in a few modules `undefined symbol: _PyEval_RequestCodeExtraIndex` occurs.

```py
test test_code crashed -- Traceback (most recent call last):
  File "test.libregrtest.runtest", line 166, in runtest_inner
    the_module = importlib.import_module(abstest)
  File "importlib", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "test.test_code", line 270, in <module>
    RequestCodeExtraIndex = py._PyEval_RequestCodeExtraIndex
  File "ctypes", line 377, in __getattr__
  File "ctypes", line 382, in __getitem__
AttributeError: /path/to/build/apps/cpython_tests/x86_64-unknown-linux-gnu/debug/cpython_tests: undefined symbol: _PyEval_RequestCodeExtraIndex
```

There may be more, as `No module named '_testcapi'` is a common error in my logs. c.f. https://github.com/indygreg/python-build-standalone/issues/15

**Comment by jayvdb** [comment]
Another: `undefined symbol: PyThreadState_SetAsyncExc`

**Comment by indygreg** [comment]
Thanks for reporting!

**Comment by kamoser** [comment]
I also ran into a similar issue using rubicon-objc. Narrowed it down to just using ctypes and referencing `ctypes.pythonapi.Py_IncRef`. Referencing from a regular python repl gives:
```python
>>> ctypes.pythonapi.Py_IncRef
<_FuncPtr object at 0x105af56d0>
```
while referencing from inside a pyoxidizer-built repl gives:
```python
>>> ctypes.pythonapi.Py_IncRef
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ctypes", line 377, in __getattr__
  File "ctypes", line 382, in __getitem__
AttributeError: dlsym(RTLD_DEFAULT, Py_IncRef): symbol not found```

if you run from a pyoxidizer-built repl but not regular

**Comment by indygreg** [comment]
I /think/ this is fixed on the current `main` branch:

```
(Pdb) import ctypes
(Pdb) ctypes.pythonapi
<PyDLL 'None', handle 7fb4cf93b190 at 0x7fb4ce516f50>
(Pdb) ctypes.pythonapi.Py_IncRef
<_FuncPtr object at 0x7fb4ce73b7a0>
```

I suspect this was a pleasant side-effect of commit 215b58749d91914ba31167ed77e36c1ac1d318fb. If so, you should be able to work around the issue in PyOxidizer 0.6 by adding a `.cargo/config` file with the following content:

```
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-Wl,-export-dynamic"]
```

Please let me know if the problem still persists in the `main` branch. We probably still need to add a similar workaround on macOS to expose the Python symbols from produced binaries...

**Comment by kamoser** [comment]
Ah, I was actually trying to build for macOS, so that doesn't work. Otherwise, I tested on windows and a Ubuntu windows subsystem and this worked.

**Comment by indygreg** [comment]
OK. I'll need to make a similar change to expose symbols on macOS. Since macOS uses Clang for linking, the config setting in `.cargo/config` might actually be identical to Linux, just for a different Rust target triple (`x86_64-apple-darwin`).

**Comment by indygreg** [comment]
I was able to get a `FuncPtr` from `ctypes.pythonapi.Py_IncRef` after applying the referenced commit. So I'm pretty sure this works now.
