### ISSUE TITLE
New projects from patched PyOxidizer fail due to wrong repo

### ISSUE THREAD

**Issue by jayvdb** [indygreg/PyOxidizer#179]
My `pyoxidizer` binary currently includes https://github.com/indygreg/PyOxidizer/pull/174 , and it injects `fb556a3136aaf63e69b93aca63a3aa2ecd4729e7` into the pyembed Cargo.toml, and then tries to fetch that from https://github.com/indygreg/PyOxidizer.git which fails because that commit is in my fork.

```console
    Updating crates.io index
    Updating git repository `https://github.com/indygreg/PyOxidizer.git`
error: failed to load source for a dependency on `cpython`

Caused by:
  Unable to update https://github.com/indygreg/PyOxidizer.git?rev=fb556a3136aaf63e69b93aca63a3aa2ecd4729e7

Caused by:
  revspec 'fb556a3136aaf63e69b93aca63a3aa2ecd4729e7' not found; class=Reference (4); code=NotFound (-3)
```

Related, 714d136 explains why rust-cpython is being vendored, but some docs about it would be good, and especially a link to the Cargo feature enhancement about this problem.

**Comment by indygreg** [comment]
I think this should work in the latest released version and in `master`, as we no longer depend on forks of 3rd party crates.
