### ISSUE TITLE
Need a mechanism to embed a Windows manifest resource

### ISSUE THREAD

**Issue by mharbison72** [indygreg/PyOxidizer#197]
Mercurial's wrapper exe gets an embedded manifest resource courtesy of setup.py, and that's needed for the Inno installer[1].

[1] https://phab.mercurial-scm.org/D7160

**Comment by indygreg** [comment]
I think https://github.com/rust-lang/rfcs/issues/721 tracks the Rust feature for this. But since PyOxidizer mostly abstracts away the existence of Rust/Cargo, we should be able to make something work here.

**Comment by indygreg** [comment]
I'm reasonably sure the implementation I just committed works. But I don't have an easy way to verify. If anyone has an old version of Windows sitting around and wants to test, by all means! I could generate an executable to test with if you want.
