### ISSUE TITLE
run command doesnt propogate app error status in repl mode

### ISSUE THREAD

**Issue by jayvdb** [indygreg/PyOxidizer#208]
When using the `run` command, if the app fails, the error code is discarded.

c.f. https://dev.azure.com/gregoryszorc/PyOxidizer/_build/results?buildId=275 on https://github.com/indygreg/PyOxidizer/pull/183

**Comment by jayvdb** [comment]
Actually this is probably due to using the repl mode, and would also occurr when running the app directly.

It does differ from how the python3 repl works with the cli wrapper.

```console
> echo 'import foobar' | python3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'foobar'
> echo $?
1
```

**Comment by indygreg** [comment]
It does not surprise me that the `repl` mode doesn't handle exit codes properly. Getting things right is hard and I only made an effort to do it for `eval` and `module`, which are the modes that matter most.
