### ISSUE TITLE
pip packaging rules should allow excludes

### ISSUE THREAD

**Issue by bsiegel** [indygreg/PyOxidizer#21]
I’m trying to package up a tool that can be installed from pip, so naturally I went with a `pip-install-simple` packaging rule. However I discovered that a transitive dependency (`include`) bundles both Python2 and Python3 modules side by side which was breaking the build. I needed to exclude the offending Python2 modules, but there is no exclude for the two pip-related packaging rules.

I solved this by switching to the `virtualenv` packaging rule which does allow specifying excludes, and just populating my virtualenv by running “pip install <packagename>”. However it would be nice if the exclude directive was allowed on the pip-related rules as well.

**Comment by indygreg** [comment]
Thanks for the report! The features for various packaging rules could definitely be improved and made consistent. This is a legitimate feature request. I'll gladly accept a pull request if someone beats me to implementing this!
