### ISSUE TITLE
How to use the new PythonDistribution config format?

### ISSUE THREAD

**Issue by m3nu** [indygreg/PyOxidizer#214]
Cool project. Just trying to package [Borg Backup](https://www.borgbackup.org) with it. I went straight to version 0.5.0 and the new config format. Some of it isn't fully documented yet and I'm not sure how to use the new syntax that was added a few days ago. How would I use the new `PythonDistribution.setup_py_install()`/`.pip_install()`?

```
embedded_python_config = EmbeddedPythonConfig()

packaging_rules = []
packaging_rules.append(Stdlib(include_source=False))
packaging_rules.append(StdlibExtensionsPolicy("all"))

dist = default_python_distribution()
dist.pip_install(["borgbackup"])  # How to proceed from here?

python_run_mode = python_run_mode_module("borg.__main__")

Config(
    application_name="borg",
    embedded_python_config=embedded_python_config,
    python_distribution=dist,
    python_run_mode=python_run_mode,
    packaging_rules=packaging_rules,
)
```

**Comment by indygreg** [comment]
Things are currently broken on the `master` branch. I hope to have functionality restored by the end of the year. But no promises. Functionality will certainly be restored by the next major release, as I don't like shipping regressions or loss of functionality. It is best to stick with 0.4 for now. Sorry about the inconvenience.

**Comment by m3nu** [comment]
No worries. Will try to make it work with 0.4 and looking forward to 0.5!
