### ISSUE TITLE
Hide shell window on Windows

### ISSUE THREAD

**Issue by adrientetar** [indygreg/PyOxidizer#216]
On Windows by default a console window is opened, how could I hide that window? It seems the recommended way is to run pythonw rather than python. Is there a way to tell pyoxidizer to hide the window?

**Comment by indygreg** [comment]
We'll need to pass something to Rust to tell it to not build a console application. According to StackOverflow: https://stackoverflow.com/questions/29763647/how-to-make-a-program-that-does-not-display-the-console-window.

You can work around this today by using `pyoxidizer init-rust-project` and modifying said Rust project to include the annotation in the top SO answer.

**Comment by indygreg** [comment]
This is now implemented in the `main` branch.
