### ISSUE TITLE
Rendering issue in Comparing to other Tools Docs

### ISSUE THREAD

**Issue by johnthagen** [indygreg/PyOxidizer#230]
There is some broken RST rendering at: https://pyoxidizer.readthedocs.io/en/latest/comparisons.html#pyinstaller

> PyInstaller is a tool to convert regular python scripts to “standalone” executables. The standard packaging produces a tiny executable and a custom directory structure to host dynamic libraries and Python code (zipped compiled bytecode). PyInstaller can produce a self-contained executable file containing your application, however, at run-time, PyInstaller will extract binary files and a custom ZlibArchive <https://pyinstaller.readthedocs.io/en/latest/advanced-topics.html#zlibarchive>`_ to a temporary directory then import modules from the filesystem. ``PyOxidizer` typically skips this step and loads modules directly from memory using zero-copy. This makes PyOxidizer executables significantly faster to start.

**Comment by indygreg** [comment]
Thanks for the report!
