### ISSUE TITLE
pyoxidizer --version outputs "PyOxidizer UNKNOWN"

### ISSUE THREAD

**Issue by touilleMan** [indygreg/PyOxidizer#232]
Upgrading from PyOxidizer 0.3.0 to 0.6.0:

```shell
$ pyoxidizer  --version
PyOxidizer 0.3.0
$ cargo uninstall pyoxidizer
    Removing /home/emmanuel/.cargo/bin/pyoxidizer
$ cargo install pyoxidizer
[...]
$ pyoxidizer --version
PyOxidizer UNKNOWN
```

I have the same result on Windows 64bits (using `nightly-x86_64-pc-windows-msvc` with rustc `1.43.0-nightly`) and on WSL using (using `nightly-x86_64-unknown-linux-gnu` with rustc `1.38.0-nightly`)

I'm guessing it's an issue from the vergen dependency since it provides the `VERGEN_SEMVER_LIGHTWEIGHT` used to display version, and the `UNKNOWN` output is generated from here:

https://github.com/rustyhorde/vergen/blob/8d522db8c8e16e26c0fc9ea8e6b0247cbf5cca84/src/output/mod.rs#L88-L95

**Comment by indygreg** [comment]
There are a handful of bugs related to version detection. I think it has to do with `vergen` trying to run `git` at build time. If you don't have `git` in your executable path (which can be common on Windows), it won't work.

This is definitely a bug. Albeit low priority (unless you feel otherwise). Thanks for reporting.

**Comment by indygreg** [comment]
I've recently made some changes to how the version string and Git commit are obtained. Could you please run `cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main pyoxidizer` and paste the output from `pyoxidizer --version`?

**Comment by touilleMan** [comment]
The --version seems fine now:
on Windows10:
```
$ pyoxidizer --version
PyOxidizer 0.8.0-pre
commit: 4697fb25918dfad6dc73288daeea501063963a08
source: https://github.com/indygreg/PyOxidizer.git
pyembed crate location: git = "https://github.com/indygreg/PyOxidizer.git", rev = "4697fb25918dfad6dc73288daeea501063963a08"
```

And Ubuntu 20.04:
```
$ pyoxidizer  --version
PyOxidizer 0.8.0-pre
commit: 4697fb25918dfad6dc73288daeea501063963a08
source: https://github.com/indygreg/PyOxidizer.git
pyembed crate location: git = "https://github.com/indygreg/PyOxidizer.git", rev = "4697fb25918dfad6dc73288daeea501063963a08"
```

**Comment by indygreg** [comment]
Excellent! Then I will consider this issue closed.
