### ISSUE TITLE
Does not support Twisted

### ISSUE THREAD

**Issue by ademilsonfp** [indygreg/PyOxidizer#241]
I cannot build a project with Twisted and tried to use this two configurations for `exe.add_in_memory_resources()`: requirements.txt and virtualenv.

The common error which is displayed is:

```
error[PYOXIDIZER_BUILD]: in-memory-only resources policy active but in-memory extension module importing not supported by this configuration
```

Removing dependant packages of Twisted one by one the project is sucessfully builded after completely remove the Twisted, but the resulted executable will not run as expected due to missing modules.

**Comment by kellyjonbrazil** [comment]
Have you tried adding `resources_policy="prefer-in-memory-fallback-filesystem-relative:lib"` to the `dist.to_python_executable()` function?

This seemed to work for me when I ran into that error.
```
def make_exe(dist):
    python_config = PythonInterpreterConfig(
        run_eval="import jc.cli; jc.cli.main()"
    )

    exe = dist.to_python_executable(
        name="jc",
        config=python_config,
        resources_policy="prefer-in-memory-fallback-filesystem-relative:lib",
        extension_module_filter='all',
        include_sources=False,
        include_resources=False,
        include_test=False
    )

    exe.add_in_memory_python_resources(dist.pip_install(["-r", "requirements.txt"]))
    return exe
```

**Comment by ademilsonfp** [comment]
As described [here](https://pyoxidizer.readthedocs.io/en/stable/config_api.html#pythondistribution-read-virtualenv-path):

_If .pth or similar mechanisms are used for installing modules, files may not be discovered properly._

Looking at my site-packages I found `zope.interface-5.1.0-py3.7-nspkg.pth` file with the above content, which I replaced  all semicolons into line breaks and tried to make it more readable:

```
has_mfs = sys.version_info > (3, 5)

p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('zope',))
importlib = has_mfs and __import__('importlib.util')

has_mfs and __import__('importlib.machinery')

m = has_mfs and sys.modules.setdefault('zope',
    importlib.util.module_from_spec(
    importlib.machinery.PathFinder.find_spec('zope', [os.path.dirname(p)])))

m = m or sys.modules.setdefault('zope', types.ModuleType('zope'))
mp = (m or []) and m.__dict__.setdefault('__path__',[])
(p not in mp) and mp.append(p)
```

Can I get around it anyway?

**Comment by ademilsonfp** [comment]
> Have you tried adding `resources_policy="prefer-in-memory-fallback-filesystem-relative:lib"` to the `dist.to_python_executable()` function?
> 
> This seemed to work for me when I ran into that error.

Thank you @kellyjonbrazil, it worked perfectly on Linux, now I'll try the same PyOxidizer build on Windows, but for now, this issue seems to be resolved.
