### ISSUE TITLE
MACOSX_DEPLOYMENT_TARGET=10.11 build doesn't run on osx 10.11

### ISSUE THREAD

**Issue by kellyjonbrazil** [indygreg/PyOxidizer#243]
I tried using `MACOSX_DEPLOYMENT_TARGET=10.11` during the build and got this when running on osx 10.11:
```
$ ./jc 
dyld: lazy symbol binding failed: Symbol not found: _getentropy
  Referenced from: /Users/kelly/Desktop/./jc
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _getentropy
  Referenced from: /Users/kelly/Desktop/./jc
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
```

**Comment by indygreg** [comment]
This is almost certainly a bug in how https://github.com/indygreg/python-build-standalone is producing the builds. A quick Google search shows that modern macOS SDK versions pull in this symbol as a weak import even if targeting an older SDK. I reckon we can work around this by actually building against an older SDK or disabling weak imports. I'll have to research this further.

**Comment by indygreg** [comment]
I believe I fixed this a while ago. Please reopen if you can still reproduce on the `main` branch. You can install the latest code via `cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main pyoxidizer`.
