### ISSUE TITLE
Python curses unicode support

### ISSUE THREAD

**Issue by Ppjet6** [indygreg/PyOxidizer#250]
Hi! I am trying to package Poezio -- [a TUI application](https://lab.louiz.org/poezio/poezio) -- and it requires unicode support in the curses distribution, but it seems PyOptimizer's Python distribution doesn't include the proper one.

PyOxidizer: 0.7.0
Python distribution downloaded: cpython-3.7.7-linux64-20200409T0045

# Steps to reproduce

- `pyoxidizer init-rust-project foo`
- `pyoxidizer run --path foo`

```python
>>> import curses
>>> hasattr(curses, 'unwch')
```

# Expected behaviour

`hasattr` returns `True`.

# What happens

The `hasattr` call returns `False`.

This can mean that Python was built against libncurses and not libncursesw. Here is the warning we return when this happens: https://lab.louiz.org/poezio/poezio/-/blob/master/poezio/poezio.py#L16.

Thanks! :)

**Comment by indygreg** [comment]
Thank you for reporting! This looks like a legit bug. The underlying project that needs patched is https://github.com/indygreg/python-build-standalone (which I also maintain). But there's no need to file a separate issue: I'll handle that.
