### ISSUE TITLE
Install from latest crate is unversioned

### ISSUE THREAD

**Issue by fgadaleta** [indygreg/PyOxidizer#257]
```pyoxidizer 
PyOxidizer UNKNOWN
Gregory Szorc <gregory.szorc@gmail.com>
Build and distribute Python applications
```

**Comment by indygreg** [comment]
Can you please run `cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main pyoxidizer` then `pyoxidizer --version` and paste the output? (I think this is fixed in the `main` branch.)

**Comment by indygreg** [comment]
Reports from others in similar issues seems to indicate this is fixed. So I'm closing this issue.
