### ISSUE TITLE
pyoxidizer.bzl incorrectly includes a `dont_write_bytecode` option

### ISSUE THREAD

**Issue by wkschwartz** [indygreg/PyOxidizer#274]
Sometimes the documentation has `write_bytecode`:

https://github.com/indygreg/PyOxidizer/blob/98d40575d21349ed1643604ba25f9de823af84ff/docs/config_api.rst#L841

This is correct:

https://github.com/indygreg/PyOxidizer/blob/98d40575d21349ed1643604ba25f9de823af84ff/pyoxidizer/src/starlark/python_interpreter_config.rs#L122

However, sometimes the documentation is wrong:

https://github.com/indygreg/PyOxidizer/blob/98d40575d21349ed1643604ba25f9de823af84ff/docs/config_api.rst#L665

And the template for `pyoxidizer.bzl` incorrectly offers `dont_write_bytecode`:

https://github.com/indygreg/PyOxidizer/blob/98d40575d21349ed1643604ba25f9de823af84ff/pyoxidizer/src/templates/new-pyoxidizer.bzl#L19

**Comment by indygreg** [comment]
Good catch! These should have been changed as part of 6677016fdc00ecabc86607c2d6e8acb668454fb5.
