### ISSUE TITLE
Can't set sys.path within PyOxidizer executable

### ISSUE THREAD

**Issue by wayne-algebraic** [indygreg/PyOxidizer#281]
I'm trying to build an executable that has a combination of proprietary modules and public modules. The proprietary modules will be loaded in memory using: 

exe.add_in_memory_python_resources(dist.read_package_root(path="<mypath>", packages=["<mypackages>"]))

I think the easiest way for me to import the public modules (eg numpy, pandas, ...) is to simply have them installed in the target environment and have them be imported at runtime. Does this make sense?

I believe it will work if my sys.path variable is set correctly. When I run the REPL generated by my pyoxidizer.bzl file is is empty.  

How do I control PyOxidizer's setting of sys.path?

Note that I'm running under MacOS.

**Comment by indygreg** [comment]
The `PythonInterpreterConfig` Starlark type accepts a `sys_paths` argument to define the initial value for `sys.path`. Search for `sys_paths` at https://pyoxidizer.readthedocs.io/en/stable/config_api.html#python-interpreter-configuration.

The autogenerated `pyoxidizer.bzl` config file should have a commented out entry for `sys_paths`.

Is this information helpful?

**Comment by indygreg** [comment]
The 0.8 release moved this setting to https://pyoxidizer.readthedocs.io/en/latest/config_type_python_interpreter_config.html#config-type-python-interpreter-config-module-search-paths.

Anyway, PyOxidizer supports setting the `sys.path` value. So I'm going to close this issue since it doesn't seem actionable.
