### ISSUE TITLE
Mention all operating systems

### ISSUE THREAD

**Issue by cool-RR** [indygreg/PyOxidizer#289]
You have to mention the operating systems you support on the readme and the first page of your documentation. I maintain [PythonTurtle](https://github.com/PythonTurtle/PythonTurtle/) which would be a good usecase for PyOxidizer, and I had to spend **10 minutes** researching PyOxidizer to figure out it supports Windows. Unless I misunderstood something about the goals of the project, which is possible, this is your customer's pain points and they must be declared front-and-center.

Something like this: 

PyOxidizer creates binaries for the major operating systems: Windows 7+, Mac OS 17+, Linux foo-bar whatever

**Comment by indygreg** [comment]
Thank you for calling out the gap in docs coverage! I'll add a clear `Operating System Requirements` section to the `Getting Started` docs page. This should show up pretty prominently in the main docs table of contents.

**Comment by cool-RR** [comment]
@indygreg Looking at the way you wrote this PR, I don't think you understood. Sorry if I'm being rude, and it's possible I didn't understand the project, please correct me if I'm making a mistake. If I understand correctly, your project allows creating binaries for Windows, Mac OS, etc. This means that people who use PyOxidizer don't have to deal with creating Windows binaries or Mac Binaries for their program, and they can delegate the entire thing to PyOxidizer, and that's the main value of PyOxidizer. Is that correct?

If that is true, then the way you did the PR is not right. It shouldn't be in "Getting started" and it shouldn't be under the title of "Operating System Requirements". It should be on the main page of the documentation, on the readme, in the first few lines, maybe in bold. It is the main value that you offer. Open-source people hate Windows. They hate dealing with platform-specific details. If you solve that pain point, you should say so very, very clearly.
