### ISSUE TITLE
No "run_repl" in pyoxidizer.bzl file

### ISSUE THREAD

**Issue by ediril** [indygreg/PyOxidizer#291]
[Customizing Python and Packaging Behavior](https://pyoxidizer.readthedocs.io/en/latest/getting_started.html#customizing-python-and-packaging-behavior) section in the docs suggests the following:

> Open pyoxidizer.bzl in your favorite editor and find the line passing a run_repl argument, which configures the embedded interpreter to run a Python REPL. Let’s replace that line with the following:
>
>run_eval="import uuid; print(uuid.uuid4())",

However there is no `run_repl` in that file. It seems like the docs are out of sync with the latest release.

There is a `python_config.run_mode` argument which seems to be the new way to do this. It seems like the docs need updating.

**Comment by indygreg** [comment]
Good catch. Thank you for reporting!
