### ISSUE TITLE
Unable to print from Starlark config

### ISSUE THREAD

**Issue by bsiegel** [indygreg/PyOxidizer#292]
Picking this project back up. Today I was trying to locate a resource that I need to exclude. I tried the following to simply dump out all the resources that were being discovered:

```
    for resource in exe.pip_install(["azure-cli==2.12.1"]):
        print(resource.name)
        exe.add_python_resource(resource)
```

However it looks like the `print` function doesn't exist:

```
error[CM01]: Variable 'print' not found
   --> ./pyoxidizer.bzl:154:9
    |
154 |         print(resource.name)
    |         ^^^^^ Variable was not found
```

The Starlark docs indicate that the print function should be available. What gives? Or, how would you go about debugging this another way?

**Comment by indygreg** [comment]
It looks like the Rust Starlark implementation only exposes `print()` if you are in Starlark REPL mode. PyOxidizer doesn't run in this mode. (Perhaps it should?)

There is a global `fail()` function that can be used to trigger an error. You can use that as a crude form of debugging.

We should definitely get a working `print()` in the Starlark environment to aid print-based debugging and extra forensic logging.
