### ISSUE TITLE
.read_virtualenv not supported for type PythonExecutable

### ISSUE THREAD

**Issue by bsiegel** [indygreg/PyOxidizer#297]
Super simple to reproduce - initialize a new config file, and uncomment the example on L170 that calls `read_virtualenv`.

Note, I tried both what was in the sample config file `.read_virtualenv(path="...")` and the syntax in the docs which is slightly different because it omits the kwarg `.read_virtualenv("...")`

PyOxidizer 0.8 / MacOS 10.15.6 / Python 3.8.5 / Rust 1.47.0

**Comment by indygreg** [comment]
Thanks for reporting. I can confirm this is an issue.
