### ISSUE TITLE
$ORIGIN seems broken

### ISSUE THREAD

**Issue by sevein** [indygreg/PyOxidizer#298]
Hi Gregory, thanks for such an amazing project!
I've been trying to build a binary but had some issues when with a dependency called jsonschema. The part in jsonschema that was problematic is [here](https://github.com/Julian/jsonschema/blob/5911287dfef6c940191277fa9dc091ce7ead3c69/jsonschema/_utils.py#L54).

Not sure if I'm going in the right direction, but I've followed your instructions in [Packaging Python Files Next to the Built Application](https://pyoxidizer.readthedocs.io/en/latest/packaging_additional_files.html) and I see the following error when I try to use `$ORIGIN`:

```
error[E0308]: mismatched types
  --> /tmp/pyoxidizer.QhyNe0hFFVuO/artifacts/default_python_config.rs:44:39
   |
44 |             module_search_paths: Some("$ORIGIN/lib"),
   |                                       ^^^^^^^^^^^^^ expected struct `std::vec::Vec`, found `&str`
   |
   = note: expected struct `std::vec::Vec<std::path::PathBuf>`
           found reference `&'static str`

error: aborting due to previous error
```

I've set up a repo where this is easily reproducible: https://github.com/sevein/jsm.

Thank you in advance!

**Comment by indygreg** [comment]
Yikes, I'm not sure how I managed to regress this one without catching it. This is a legit bug. I'll get this fixed today. Thanks for reporting.

**Comment by indygreg** [comment]
I've pushed a fix to the `main` branch. You can install the main branch via `cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main pyoxidizer`. The `main` branch is usually pretty stable. And there are not yet any backwards incompatible Starlark changes committed to it.

**Comment by sevein** [comment]
That was fast, thank you!
