### ISSUE TITLE
Typo in 'How Is This Different Than PyInstaller' section

### ISSUE THREAD

**Issue by JMB2K** [indygreg/PyOxidizer#3]
Hi...I'm new to contributing and was getting an 'access denied' type of error when I was attempting to do this another way, as I've corrected the file already, but there seems to be a typo in this section...I believe the highlighted word should actually be PyInstaller, correct?

![pyox](https://user-images.githubusercontent.com/24712073/50576817-b3632c80-0ddf-11e9-8e10-c26f3403d6fd.jpg)

**Comment by indygreg** [comment]
This was fixed by 6cbfefdac4f4677b9fa4b4495fc80cd4a07fbd1f.
