### ISSUE TITLE
glob might have stopped working

### ISSUE THREAD

**Issue by sevein** [indygreg/PyOxidizer#300]
Hi again! You've been making exciting progress.
Running [main](https://github.com/indygreg/PyOxidizer/commit/0b8fd24709c38df0b5eb0c50a1baad1fdb77b30c), I haven't been able to combine FileManifest.add_manifest() and glob(). This is what I am seeing:

```
error[CV02]: function expects a list for include; got type string
  --> ./pyoxidizer.bzl:36:17
   |
36 |     templates = glob("/path/to/project/templates/**/*", strip_prefix="/path/to/project/")
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected type list; got string
```

**Comment by indygreg** [comment]
The first argument to `glob()` should be a `list[string]`. It looks like the example in the docs is wrong.
