### ISSUE TITLE
oxidized_importer.find_resources_in_path Doesn't Load pyc Ffiles

### ISSUE THREAD

**Issue by charleseidsness** [indygreg/PyOxidizer#301]
I would like to evaluate oxidized_importer on an embedded system which only has pyc files; no py files, for most modules but oxidized_importer.find_resources_in_path doesn't seem load them.

I was expecting them to be loaded as a PythonModuleBytecode.

Is this something that is expected? Does it only support py source files?

Thanks!

**Comment by indygreg** [comment]
`oxidized_importer.find_resources_in_path()` does return `PythonModuleBytecode` instances. And https://github.com/indygreg/PyOxidizer/blob/ddcf676d5ca42e5fce0d2f31f6ca2fb97b82a2c1/pyembed/src/test/test_importer_resource_scanning.py#L48 is a test to prove it.

However, it may not work reliably in all cases. For example, internally it uses `importlib.machinery.*_SUFFIXES` to determine which extensions map to different Python resource types. If there is a mismatch between the running interpreter and the interpreter in your embedded context, it may fail to pick things up.

https://pyoxidizer.readthedocs.io/en/v0.9.0/managing_projects.html#debugging-resource-scanning-and-identification-with-find-resources may help with tracking down exactly what isn't working here. If you provide steps to reproduce with a clear failing scenario, that will make it easier on me to identify the cause and fix.

**Comment by charleseidsness** [comment]
Thanks!

It's probably related to cross-compiling for my embedded system then.

Something came up and I'll need to pause this project for a week but I'll cycle back to it using those debug features.

**Comment by charleseidsness** [comment]
I see what my problem is. My pyc files are in the main module directory, ie.:
/lib/python3.9/site-packages/psutil/__init__.pyc

Not in the __pycache__ directory with ethe cache name ie:
/lib/python3.9/site-packages/psutil/__pycache__/__init__.cpython-39.pyc

It looks like this may be a limitation of find_python_resources from python_packaging.

That's unfortunate, it is fairly common for embedded systems to only include pre-built pyc files to improve load times but not increase the total size of the package with having both pyc and py files.

I'll have a look at my build system, ultimately it wouldn't make sense to include py or pyc files on my target system anyways if I am using oxidized_resources instead so this will become a non-issue. Now that I'm aware of this limitation I can keep going.
