### ISSUE TITLE
Unable to call has_attr()

### ISSUE THREAD

**Issue by href** [indygreg/PyOxidizer#329]
I'm trying to run the latest master build, created as follows:

```bash
$ cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main pyoxidizer
```

When I build the default config created by `pyoxidizer init-config-file` I hit the following error after a while:

```bash
$ cargo build
...
dev [unoptimized + debuginfo] target(s) in 46.84s
error: unable to call has_attr()
```

Should I be doing something differently? The latest release works, but I hit some issues with and wanted to try out the latest master to see if some of them might have been solved already.

**Comment by indygreg** [comment]
This appears to have regressed in a84d6cf1fa3835fea2ab450bcb93739d50084086. I'll try to get a fix pushed in the next few days.
