### ISSUE TITLE
Python3.dll should be included as well as python3Y.dll

### ISSUE THREAD

**Issue by mharbison72** [indygreg/PyOxidizer#336]
My understanding is that it's just a stub that re-exports python3Y.dll, but it is needed to make pygit2 work on Windows.  The build directory for Mercurial currently contains:

```
$ ls -l ../build/pyoxidizer/x86_64-pc-windows-msvc/release/app_windows/
total 32661
-rwxr-xr-x  1 Matt Administrators 29147648 Dec  1 22:04 hg.exe
drwxr-xr-x 34 Matt Administrators    20480 Dec  1 22:04 lib
-rwxr-xr-x  1 Matt Administrators  4216832 Dec  1 22:04 python38.dll
```

If I copy the file there from a python3.8 install, pygit2 initializes.  The easiest way to test is to check the version using the current Mercurial default branch:

```
$ ../build/pyoxidizer/x86_64-pc-windows-msvc/release/app_windows/hg.exe version -v --config extensions.git=
Mercurial Distributed SCM (version 5.6+223-f3cf575bbb38)
(see https://mercurial-scm.org for more information)

Copyright (C) 2005-2020 Matt Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Enabled extensions:

  absorb       internal
  blackbox     internal
  extdiff      internal
  fix          internal
  git          internal  (pygit2 1.4.0)
  phabblocker  external
  phabricator  internal
  rebase       internal
  show         internal
  strip        internal
```

It will say `(pygit2 N/A)` if the dll is unavailable.

This probably affects other things, and I'm wondering if it is related to https://github.com/indygreg/PyOxidizer/issues/75#issuecomment-736543582, based on this:

https://stackoverflow.com/questions/42863505/dll-load-failed-when-importing-pyqt5

**Comment by indygreg** [comment]
Yes, we should probably include `python3.dll` when using the dynamically linked Python distribution.

**Comment by mharbison72** [comment]
That worked, thanks!  Does the "dynamically linked" qualifier mean that extensions depending on this can't be used with the all-in-one executable?  (IDK how that works- I was under the impression that the DLLs were just loaded from the process image in memory, but I also thought I read at some point that python was being built statically, and in one of the PyQt related issues you mentioned probably having to build from source.)
