### ISSUE TITLE
Use 32-bit DLLs in 64-bit Python

### ISSUE THREAD

**Issue by fleimgruber** [indygreg/PyOxidizer#341]
What would be the recommended approach to use 32-bit DLLs in 64-bit Python with PyOxidizer? Is this even possible / supported? Currently using `msl-loadlib` according to [these](https://msl-loadlib.readthedocs.io/en/latest/interprocess_communication.html) docs.

**Comment by indygreg** [comment]
If this is for Windows, if you are using the default Python distributions, I would guess loading 32-bit DLLs would work like any other application. Does it not?

**Comment by fleimgruber** [comment]
In the end I used another solution, but was and still am curious so I might just try this at a future point in time - thanks for checking back and your answer in any case!
