### ISSUE TITLE
Can I apply it to pack a tensorflow-based python program and distribute it?

### ISSUE THREAD

**Issue by temco** [indygreg/PyOxidizer#35]
Or other AI lib such as pytorch, keras, etc.?

**Comment by silverjam** [comment]
Not yet.

Tensorflow uses numpy, numpy uses __file__ so it's not going to work until NumPy is fixed to use the resource loader API: https://pyoxidizer.readthedocs.io/en/latest/packaging_pitfalls.html#reliance-on-file.  NumPy and Tensorflow use C extensions, which are not explicitly supported yet: https://pyoxidizer.readthedocs.io/en/latest/status.html#c-extensions.

Will likely fail like this:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow", line 28, in <module>
  File "tensorflow.python", line 47, in <module>
  File "numpy", line 126, in <module>
  File "numpy.__config__", line 10, in <module>
NameError: name '__file__' is not defined
```

**Comment by indygreg** [comment]
I would very much like NumPy to work with PyOxidizer once PyOxidizer's C extension story is better.

Would someone be willing to file an issue against the NumPy project to track them moving away from `__file__` and to the modern resource API? Feel free to mention me on the issue so I can engage with the NumPy developers on the matter.

**Comment by temco** [comment]
ok, thank you for your support
