### ISSUE TITLE
Small mistake in 'Getting Started' tutorial

### ISSUE THREAD

**Issue by adideutsch** [indygreg/PyOxidizer#357]
Following this [pull request](https://github.com/indygreg/PyOxidizer/pull/320), in [this paragraph](https://pyoxidizer.readthedocs.io/en/stable/getting_started.html#customizing-python-and-packaging-behavior), this line is out of date:

> In addition, set the python_config.run_code attribute to execute pyflakes:

I think it should be changed to:

> In addition, set the python_config.**run_command** attribute to execute pyflakes:

**Comment by indygreg** [comment]
I'm no longer seeing any references to `run_code` in the docs. So this appears to have been fixed without attribution to this issue. Thank you for reporting it though!
