### ISSUE TITLE
Cannot use multiprocessing in tk app

### ISSUE THREAD

**Issue by Schmetzler** [indygreg/PyOxidizer#362]
Hello,
I want to package a tkinter app and I need to/want to use `multiprocessing.Process`. But it does not work, when I start my process just another instance of my UI is started.

I am currently on Windows 10 using python 3.8.7, pyoxidizer is version 0.10.3 and rust is 1.49.0.

I have a minimal example for the problem:

`main.py`

```
import sys
import tkinter as tk
from tkinter import ttk
import multiprocessing


def process(string):
    print(string)


def run_process():
    proc = multiprocessing.Process(
        target=process, args=("Hello",)
    )
    proc.start()


if __name__ == "__main__":
    root = tk.Tk()
    frame = ttk.Frame(root)
    frame.pack()
    ttk.Button(frame, text="Click Me", command=run_process).pack()
    tk.mainloop()
```

`pyoxidizer.bzl`

```
def make_dist():
    return default_python_distribution()

def make_exe(dist):
    policy = dist.make_python_packaging_policy()
    python_config = dist.make_python_interpreter_config()
    python_config.filesystem_importer = True
    python_config.run_filename = "main.py"

    exe = dist.to_python_executable(
        name="testapp",
        packaging_policy=policy,
        config=python_config,
    )

    exe.tcl_files_path = "lib"
    return exe

def make_embedded_resources(exe):
    return exe.to_embedded_resources()

def make_install(exe):
    files = FileManifest()
    files.add_python_resource(".", exe)
    return files

register_target("dist", make_dist)
register_target("exe", make_exe, depends=["dist"])
register_target("resources", make_embedded_resources, depends=["exe"], default_build_script=True)
register_target("install", make_install, depends=["exe"], default=True)

resolve_targets()

# END OF COMMON USER-ADJUSTED SETTINGS.
#
# Everything below this is typically managed by PyOxidizer and doesn't need
# to be updated by people.

PYOXIDIZER_VERSION = "0.10.3"
PYOXIDIZER_COMMIT = "UNKNOWN"
```

Now I run:
`pyoxidizer build`
`.\build\...\testapp.exe`

And I click the "Click Me" Button.

### What should happen:
"Hello" should be printed on console

### What happens:
The UI is spawned again.

**Comment by wkschwartz** [comment]
Note Python's [warning](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods):
> **Warning**: The `'spawn'` and `'forkserver'` start methods cannot currently be used with “frozen” executables (i.e., binaries produced by packages like **PyInstaller** and **cx_Freeze**) on Unix. The `'fork'` start method does work. 

Only the `'spawn'` start method is available on Windows. I'm guessing you can manually implement the `--multiprocessing-fork` flags defined in [`multiprocessing.spawn.get_command_line`](https://github.com/python/cpython/blob/01faf4542a8652adfbd3b3f897ba718e8ce43f5e/Lib/multiprocessing/spawn.py#L78-L89) until this gets solved.
