### ISSUE TITLE
Build fails with setuptools-51.1.1 error

### ISSUE THREAD

**Issue by bryab** [indygreg/PyOxidizer#363]
This occurs for me when trying to use `exe.add_python_resources(exe.read_package_root(...` etc.

```
thread 'main' panicked at 'unable to get directory entry: Error { depth: 14, inner: Io { path: Some(".\\build\\python_distributions\\python.8fbd66f2ff97\\python\\install\\Lib\\site-packages\\setuptools-51.1.1-py3.8.egg\\pkg_resources\\tests\\data\\my-test-package_unpacked-egg\\my_test_package-1.0-py3.7.egg\\EGG-INFO"), err: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." } } }', C:\Users\bfordney\.cargo\registry\src\github.com-1ecc6299db9ec823\python-packaging-0.3.0\src\filesystem_scanning.rs:117:35
```

**Comment by bryab** [comment]
I believe this issue might be fixed with a later version of setuptools (or older), but I'm unsure how to specify a different version of setuptools, if that is possible?

**Comment by ryancinsight** [comment]
Why are you trying to use a Python 3.7 egg with Python 3.8? 

“ my_test_package-1.0-py3.7.egg”

**Comment by bryab** [comment]
That is not my doing.  It seems like that simply exists in their repository, but is being distributed by accident.  I think they fixed it in a later version.  here's where that file is in 51.1.1:

https://github.com/pypa/setuptools/tree/60c341b82f3ddb188823405225ec5cd5b217784c/pkg_resources/tests/data/my-test-package_unpacked-egg/my_test_package-1.0-py3.7.egg

**Comment by ryancinsight** [comment]
Interesting... well what are you trying to point to? I would only really use the read_package_root for your main code or main scripts .py/pyd. 

If it is just a .py or pyd can you show example of how you are imputing path? It's easier to place file next to .bzl and just use path="." and package = "name_no_extension"

**Comment by bryab** [comment]
Aha!  I misunderstood the problem.  My code was:

```
exe.add_python_resources(exe.read_package_root(
       path=".",
       packages=["testmod"],
    ))
```

But this was making it scan the entire directory, including the "build" directory.  I have moved my code to a "src" folder and this now works.

**Comment by bryab** [comment]
> 
> 
> Interesting... well what are you trying to point to? I would only really use the read_package_root for your main code or main scripts .py/pyd.
> 
> If it is just a .py or pyd can you show example of how you are imputing path? It's easier to place file next to .bzl and just use path="." and package = "name_no_extension"

Can you show me an example of what you mean, instead of what I pasted above?
