### ISSUE TITLE
OpenCV ImportError libpng15

### ISSUE THREAD

**Issue by B3QL** [indygreg/PyOxidizer#365]
Hi,
thank you for the huge effort in solving the Python application distribution problem.

I encountered a strange error trying to build a project with `opencv-python-headless==4.5.1.48`

```
installing files to /home/personal/Code/bug/./build/x86_64-unknown-linux-gnu/debug/install
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "cv2", line 5, in <module>
ImportError: libpng15-c2ffaf3d.so.15.13.0: cannot open shared object file: No such file or directory
error: cargo run failed
```
OS: Fedora 32
PyOxidizer 0.10.3
commit: unknown
source: https://github.com/indygreg/PyOxidizer.git
pyembed crate location: version = "0.10.3"

Is there any kind of workaround for it?

`pyoxidizer.bzl`
```
def make_dist():
    return default_python_distribution()

def make_exe(dist):
    policy = dist.make_python_packaging_policy()
    policy.resources_location = "filesystem-relative:libs"
    python_config = dist.make_python_interpreter_config()
    python_config.run_command = "import cv2"
    exe = dist.to_python_executable(
        name="bug",

        # If no argument passed, the default `PythonPackagingPolicy` for the
        # distribution is used.
        packaging_policy=policy,

        # If no argument passed, the default `PythonInterpreterConfig` is used.
        config=python_config,
    )
    exe.add_python_resources(exe.pip_install(["opencv-python-headless==4.5.1.48"]))
    return exe

def make_embedded_resources(exe):
    return exe.to_embedded_resources()

def make_install(exe):
    # Create an object that represents our installed application file layout.
    files = FileManifest()

    # Add the generated executable to our install layout in the root directory.
    files.add_python_resource(".", exe)

    return files

# Tell PyOxidizer about the build targets defined above.
register_target("dist", make_dist)
register_target("exe", make_exe, depends=["dist"])
register_target("resources", make_embedded_resources, depends=["exe"], default_build_script=True)
register_target("install", make_install, depends=["exe"], default=True)

# Resolve whatever targets the invoker of this configuration file is requesting
# be resolved.
resolve_targets()

# END OF COMMON USER-ADJUSTED SETTINGS.
#
# Everything below this is typically managed by PyOxidizer and doesn't need
# to be updated by people.

PYOXIDIZER_VERSION = "0.10.3"
PYOXIDIZER_COMMIT = "UNKNOWN"
```

**Comment by ryancinsight** [comment]
Yes there is, first change libs to lib and make sure you set module_search_paths as below. Third I find it easiest to use the version I wrote for pip install below in order to add packages and specify locations.

    # Use in-memory location for adding resources by default.
    policy.resources_location = "in-memory"

    # Attempt to add resources relative to the built binary when
    # `resources_location` fails.
    policy.resources_location_fallback = "filesystem-relative:lib"


    # This variable defines the configuration of the embedded Python
    # interpreter. By default, the interpreter will run a Python REPL
    # using settings that are appropriate for an "isolated" run-time
    # environment.
    #
    # The configuration of the embedded Python interpreter can be modified
    # by setting attributes on the instance. Some of these are
    # documented below.
    python_config = dist.make_python_interpreter_config()

    # Make the embedded interpreter behave like a `python` process.
    # python_config.config_profile = "python"

    # Set initial value for `sys.path`. If the string `$ORIGIN` exists in
    # a value, it will be expanded to the directory of the built executable.
    python_config.module_search_paths = ["$ORIGIN/lib"]



    #python_config.run_command = "import cv2"

    # Run a Python module as __main__ when the interpreter starts.
    # python_config.run_module = "<module>"

    # Run a Python file when the interpreter starts.
    # python_config.run_filename = "/path/to/file"

    # Produce a PythonExecutable from a Python distribution, embedded
    # resources, and other options. The returned object represents the
    # standalone executable that will be built.
    exe = dist.to_python_executable(
        name="opencv",

        # If no argument passed, the default `PythonPackagingPolicy` for the
        # distribution is used.
        packaging_policy=policy,

        # If no argument passed, the default `PythonInterpreterConfig` is used.
        config=python_config,
    )


    # Invoke `pip install` using a requirements file and add the collected resources
    # to our binary.
    for resource in exe.pip_install(["opencv-python-headless==4.5.1.48"]):
        resource.add_location = "filesystem-relative:lib"
        exe.add_python_resource(resource)

    return exe

**Comment by ryancinsight** [comment]
also dont just import cv2, it will do this and then shutdown, make sure your whole command or script is written as main or just use the reprl that is made to prototype. otherwise run_command can be used for scripts you wrote that have no main.

**Comment by B3QL** [comment]
@ryancinsight thanks for checking out. After I adjusted the build script with the provided example I still encounter the same error.

Maybe I wasn't clear enough, so let me fix that. The project is building correctly without any error. However, importing the `cv2` module in runtime (via an interpreter or hardcoded import statement) raises the missing lib error. I've tried to install system libraries with no success. Even @matzim95 tried to rebuild the project on the latest Ubuntu and still failed to import `cv2`.

@ryancinsight Is the import working on your binary? Can you share the whole content of `pyoxidizer.bzl` file?

**Comment by ryancinsight** [comment]
Ah, I stand corrected, it looks like it works on windows but not Ubuntu but the issue here is a third party libpng package and the so's required are older than the libpng16 on dev. If you want your package to be portable it would probably be better to build opencv yourself and statically link png. -DBUILD_PNG=ON -DWITH_PNG=ON     //link in libpng statically from 3rdparty folder

**Comment by ryancinsight** [comment]
@B3QL @matzim95 it seems that ubuntu requires a few extra lines, first add numpy to your pip import and then add:
    policy.extension_module_filter = "all"
    policy.allow_files = True
    policy.set_resource_handling_mode("files") *pretty sure this is most important of these

Best regards and bzl zipped and attached

[pyoxidizer.zip](https://github.com/indygreg/PyOxidizer/files/5936924/pyoxidizer.zip)

**Comment by B3QL** [comment]
@ryancinsight thank you! the `policy.set_resource_handling_mode("files") ` does the job ;)
