### ISSUE TITLE
Dependency not able to be imported in generated executable

### ISSUE THREAD

**Issue by idahogray** [indygreg/PyOxidizer#378]
I am getting the following error when running the generated executable using `pyoxidizer run`.

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "checksumdir", line 19, in <module>
>   File "pkg_resources", line 886, in require
>   File "pkg_resources", line 772, in resolve
> pkg_resources.DistributionNotFound: The 'checksumdir' distribution was not found and is required by the application

I am trying to package one of my applications where the dependencies are managed using poetry. One of the dependencies is [checksumdir](https://pypi.org/project/checksumdir/). I can see this dependency getting installed by pyoxidizer.

> Successfully installed PyYAML-5.4.1 calc-to-settings-2020.3.1a1 certifi-2020.12.5 chardet-4.0.0 checksumdir-1.2.0 click-7.1.2 et-xmlfile-1.0.1 idna-2.10 openpyxl-3.0.7 requests-2.25.1 sel-api-client-2021.2.19 tabulate-0.8.9 urllib3-1.26.4

The only thing I noticed that looks odd is that checksumdir puts most of the logic in the __init__.py file. I am not sure if that causes a problem or not. I am happy to submit a bug report to that repo if it turns out to be an issue in that project. Any troubleshooting pointers would be greatly appreciated.

**Comment by indygreg** [comment]
The run-time failure is in `pkg-resources`. Unfortunately, PyOxidizer doesn't have good support for the `pkg_resources` APIs. This is documented at https://pyoxidizer.readthedocs.io/en/stable/oxidized_importer_resource_files.html?highlight=pkg_resources#support-for-pkg-resources. So this might be a duplicate of #236.

**Comment by idahogray** [comment]
Thank you, I should have paid closer attention to the error. I will try to submit a PR to the checksumdir project to see if they will try something else here.

**Comment by indygreg** [comment]
Ideally they would use the newer resource APIs in Python’s stdlib, yes. But compatibility with older Pythons is a valid excuse.

I’m also adding support for pkg_resources to PyOxidizer. I think it is an important enough feature holding people back. I may have that implemented by the end of the day (check the ci-test branch for a partial implementation).

**Comment by lauhayden** [comment]
I just ran into this exact error today, on the `unitypack`  package. I'm guessing by 0.14.0 release notes that this use case is supposed to be supported by now - should I open a new issue? The specific place that package uses `pkg_resources` is here: https://github.com/HearthSim/UnityPack/blob/f8cdc2516538d189606a76986ad2d71c3fad5f8b/unitypack/__init__.py

I will patch it out in the meantime (this is a trivial use of `pkg_resources`)
