### ISSUE TITLE
Does PyOxidizer protect the original codebase?

### ISSUE THREAD

**Issue by AjawadMahmoud** [indygreg/PyOxidizer#38]
I just came to know about this ambitious project yesterday. I started having hands-on with it, but I realised I need to ask this first, does PyOxidizer protect the original codebase?

IOW, can I use PyOxidizer to securely distribute codebase that is otherwise exposed as plain text (*.py) files? I used to compile Python libs into C libs and then write simple C program to achieve the same. Is this something PyOxidizer can do as well, even if it's not the actual use case for it?

**Comment by silverjam** [comment]
Doesn't seem like it.  The .py files or .pyc files are inlined into the binary that's produced and then read from memory.  From the docs:

> Second is the ability to import .py/.pyc files from memory. Most other self-contained Python applications rely on Python’s zipimporter or do work at run-time to extract the standard library to a filesystem (typically a temporary directory or a FUSE filesystem like SquashFS). What PyOxidizer does is expose the .py/.pyc modules data to the Python interpreter via a Python extension module built-in to the binary. In addition, the importlib._bootstrap_external module (which is frozen into libpython) is replaced by a modified version that defines a custom module importer capable of loading Python modules from the in-memory data structures exposed from the built-in extension module.

Theoretically you could extract the py or pyc file from the binary somehow.

**Comment by AjawadMahmoud** [comment]
This answers the question. Thanks.

**Comment by indygreg** [comment]
This is correct: PyOxidizer does not apply any code obfuscation techniques. I know other tools in this space support some code obfuscation. And I'm not opposed to adding code obfuscation features to PyOxidizer.

That being said, code obfuscation techniques simply raise the bar to reconstructing and understanding the original source code. Determined individuals will still figure out how things work. So obfuscation isn't safe from a security perspective. But it can be useful in industrial settings, where deterring a competitor from understanding or reverse engineering your program may be desired.

I would definitely consider adding code obfuscation to PyOxidizer!

**Comment by AjawadMahmoud** [comment]
Thanks for your reply, @indygreg. I didn't intend to request a feature that is not considered by you at this early stage of the project, but since you are here and bringing this up, I applaud you for it and appreciate your reply.
I would definitely benefit a lot from such a feature.

**Comment by indygreg** [comment]
No problem! I'll add that Python code obfuscation is not something I am very familiar with. So if someone posts details on implementations, best practices, etc, it would help tremendously. Even if we don't implement that feature soon, it is useful to know what code obfuscation might look like so we can implement things with that feature in mind.

**Comment by AjawadMahmoud** [comment]
Alright, @indygreg.
What about reformatting this issue into a a feature request and keep as to follow this?

**Comment by jkbgbr** [comment]
@indygreg I think this is one aspect is missing (or at least not really elaborated) on the [Comparisons](https://pyoxidizer.readthedocs.io/en/stable/pyoxidizer_comparisons.html) page. 

I just started to explore the possibilities available to _securely_ deploy my code to my client and I'm struggling with nuitka (there is not much information to find on details so including popular packages like matplotlib or numpy can be a PIA) but it is also not clear, at least for me, from the comparisons how the alternatives fare in this aspect.
For me simply making reverse engineering harder than extracting the source code from a zip would suffice.

Could you extend the comparisons page with some rudimentary information how PyOxidizer compares with the alternatives?
