### ISSUE TITLE
[CMS] Signer's common name unable to be parsed from some signatures

### ISSUE THREAD

**Issue by chenxiaolong** [indygreg/PyOxidizer#386]
It seems that the signer's common name is unable to be parsed from some CMS signatures. I'm attempting to parse this sample file: 
[output.ko.sig.gz](https://github.com/indygreg/PyOxidizer/files/6370900/output.ko.sig.gz) (gzip-compressed due to GitHub upload limitations). It is a DER-encoded CMS signature from one of Fedora's signed kernel modules.

I created a minimal program to reproduce the problem: https://gist.github.com/chenxiaolong/683f7813ea2b1867a27ad6c4b06f1b0a I've tried both version 0.1.0 of `cryptographic-message-syntax` and the latest commit (66bcef6b9c1e1b780f4c67c98af91699871084c2 as of writing this).

Using the sample program, I get:
```
DN: RelativeDistinguishedName(RelativeDistinguishedName([AttributeTypeAndValue { typ: Oid(b"U\x04\n"), value: [ 0c 06 46 65  64 6f 72 61  ] }]))
Common name: Ok(None)
```

With openssl, I'm able to see the common name using both the CMS API and the ASN1 API:

<details>
<summary><code>openssl cms -inform der -in output.ko.sig -cmsout -noout -print</code></summary>

```
CMS_ContentInfo: 
  contentType: pkcs7-signedData (1.2.840.113549.1.7.2)
  d.signedData: 
    version: 1
    digestAlgorithms:
        algorithm: sha256 (2.16.840.1.101.3.4.2.1)
        parameter: <ABSENT>
    encapContentInfo: 
      eContentType: pkcs7-data (1.2.840.113549.1.7.1)
      eContent: <ABSENT>
    certificates:
      <ABSENT>
    crls:
      <ABSENT>
    signerInfos:
        version: 1
        d.issuerAndSerialNumber: 
          issuer: O=Fedora, CN=Fedora kernel signing key/emailAddress=kernel-team@fedoraproject.org
          serialNumber: 0x680B1866C660ED4AC402911ECD005D345CF01040
        digestAlgorithm: 
          algorithm: sha256 (2.16.840.1.101.3.4.2.1)
          parameter: <ABSENT>
        signedAttrs:
          <ABSENT>
        signatureAlgorithm: 
          algorithm: rsaEncryption (1.2.840.113549.1.1.1)
          parameter: NULL
        signature: 
          0000 - 35 6f 7a 34 0d 9d 12 ba-04 50 b2 5b 22 e3 25   5oz4.....P.[".%
          000f - 74 59 07 9b 67 cf 5b 55-f8 23 09 de 6d bc 9c   tY..g.[U.#..m..
          001e - 10 19 44 5e b0 6a bd b5-6c ad 98 f8 21 ad a5   ..D^.j..l...!..
          002d - f4 8b 37 76 fd ae 3a c7-04 8f 69 c9 0f c5 28   ..7v..:...i...(
          003c - 98 22 0d 36 9d 30 f1 3c-0e d4 fc 12 18 ee 7e   .".6.0.<......~
          004b - f2 e6 02 17 26 48 e7 1d-4d 2c a1 0c 01 17 f7   ....&H..M,.....
          005a - b8 d2 d4 2d 73 54 7d 19-b8 f4 37 9d 68 ac d8   ...-sT}...7.h..
          0069 - b2 41 91 05 04 4d 2f 54-2b 3c b7 2a 8e 47 59   .A...M/T+<.*.GY
          0078 - 62 fb 76 9c 55 27 5f 54-a0 14 83 a4 35 de 81   b.v.U'_T....5..
          0087 - 5a dc 7e cc 65 e0 6f 0a-f1 73 29 2d 9e 79 c5   Z.~.e.o..s)-.y.
          0096 - 8b ab 29 07 0b 1f b9 7c-26 3f f3 85 33 aa 96   ..)....|&?..3..
          00a5 - 9e 85 b3 6a 1f d1 0a c4-f7 c3 f2 f8 77 df 98   ...j........w..
          00b4 - 41 e5 77 35 dc 2b 37 a1-33 a6 09 17 0f 9b f6   A.w5.+7.3......
          00c3 - b2 97 35 99 e2 3b cb 0e-01 ad 90 6a 99 7e 52   ..5..;.....j.~R
          00d2 - d7 5f 30 8c fd 22 02 4a-34 d2 f3 1b 73 52 1f   ._0..".J4...sR.
          00e1 - 31 32 9c 41 14 4e fc 5c-62 22 a7 07 ac 45 23   12.A.N.\b"...E#
          00f0 - f9 4d bb 4b 73 45 5f b4-bc 69 b7 92 59 d9 0b   .M.KsE_..i..Y..
          00ff - be 6e 9b d8 5c a8 9a 19-89 d2 00 66 0e 33 1d   .n..\......f.3.
          010e - 28 43 20 01 31 64 8f 90-44 f8 4b 5b 03 00 7a   (C .1d..D.K[..z
          011d - e2 16 81 35 d8 b6 b4 2d-3f 94 50 71 ba 9b 02   ...5...-?.Pq...
          012c - 78 1a c5 34 8a 24 c8 0b-f6 70 a1 53 0d 03 9c   x..4.$...p.S...
          013b - b3 77 23 ca 04 67 4f 7f-86 c5 b9 1a c4 d8 96   .w#..gO........
          014a - c1 85 d1 51 27 c5 60 cb-17 da 0b 87 fa 3f 92   ...Q'.`......?.
          0159 - f5 52 b6 bd 0c 8e 45 eb-80 61 63 72 29 82 88   .R....E..acr)..
          0168 - e1 5c 3b fd ff e0 d7 04-1d 94 8f 24 7d 4b 14   .\;........$}K.
          0177 - ad b2 b4 e9 47 e1 de 56-4f 66 0f 0e 64 52 01   ....G..VOf..dR.
          0186 - c7 7f 3f 87 99 39 7c de-e4 b7 af f3 fb 8c d7   ..?..9|........
          0195 - b0 04 68 2e 03 bf 96 fe-c8 8e 08 8b 1b 3a d7   ..h..........:.
          01a4 - 8d 37 ca 62 18 ce 30 a1-bc 41 15 e5 7e 81 e2   .7.b..0..A..~..
          01b3 - 3a ec 0b 59 2f 35 1b 32-f6 bb 2a 7d cd 36 7c   :..Y/5.2..*}.6|
          01c2 - c1 40 78 7a 42 4a 70 09-43 a9 4c 1c 88 ee 70   .@xzBJp.C.L...p
          01d1 - ed 45 41 42 3a ea 17 33-c5 0f 02 aa ff f5 be   .EAB:..3.......
          01e0 - cc b9 b0 e3 22 31 f2 e9-e3 d4 33 f6 2b c0 c9   ...."1....3.+..
          01ef - 5c 04 4f ad 35 b1 1d d4-22 68 82 b9 47 ad 6e   \.O.5..."h..G.n
          01fe - 76 66                                          vf
        unsignedAttrs:
          <ABSENT>
```
</details>

<details>
<summary><code>openssl asn1parse -i -in output.ko.sig -inform der</code></summary>

```
    0:d=0  hl=4 l= 730 cons: SEQUENCE          
    4:d=1  hl=2 l=   9 prim:  OBJECT            :pkcs7-signedData
   15:d=1  hl=4 l= 715 cons:  cont [ 0 ]        
   19:d=2  hl=4 l= 711 cons:   SEQUENCE          
   23:d=3  hl=2 l=   1 prim:    INTEGER           :01
   26:d=3  hl=2 l=  13 cons:    SET               
   28:d=4  hl=2 l=  11 cons:     SEQUENCE          
   30:d=5  hl=2 l=   9 prim:      OBJECT            :sha256
   41:d=3  hl=2 l=  11 cons:    SEQUENCE          
   43:d=4  hl=2 l=   9 prim:     OBJECT            :pkcs7-data
   54:d=3  hl=4 l= 676 cons:    SET               
   58:d=4  hl=4 l= 672 cons:     SEQUENCE          
   62:d=5  hl=2 l=   1 prim:      INTEGER           :01
   65:d=5  hl=2 l= 123 cons:      SEQUENCE          
   67:d=6  hl=2 l=  99 cons:       SEQUENCE          
   69:d=7  hl=2 l=  15 cons:        SET               
   71:d=8  hl=2 l=  13 cons:         SEQUENCE          
   73:d=9  hl=2 l=   3 prim:          OBJECT            :organizationName
   78:d=9  hl=2 l=   6 prim:          UTF8STRING        :Fedora
   86:d=7  hl=2 l=  34 cons:        SET               
   88:d=8  hl=2 l=  32 cons:         SEQUENCE          
   90:d=9  hl=2 l=   3 prim:          OBJECT            :commonName
   95:d=9  hl=2 l=  25 prim:          UTF8STRING        :Fedora kernel signing key
  122:d=7  hl=2 l=  44 cons:        SET               
  124:d=8  hl=2 l=  42 cons:         SEQUENCE          
  126:d=9  hl=2 l=   9 prim:          OBJECT            :emailAddress
  137:d=9  hl=2 l=  29 prim:          IA5STRING         :kernel-team@fedoraproject.org
  168:d=6  hl=2 l=  20 prim:       INTEGER           :680B1866C660ED4AC402911ECD005D345CF01040
  190:d=5  hl=2 l=  11 cons:      SEQUENCE          
  192:d=6  hl=2 l=   9 prim:       OBJECT            :sha256
  203:d=5  hl=2 l=  13 cons:      SEQUENCE          
  205:d=6  hl=2 l=   9 prim:       OBJECT            :rsaEncryption
  216:d=6  hl=2 l=   0 prim:       NULL              
  218:d=5  hl=4 l= 512 prim:      OCTET STRING      [HEX DUMP]:356F7A340D9D12BA0450B25B22E3257459079B67CF5B55F82309DE6DBC9C1019445EB06ABDB56CAD98F821ADA5F48B3776FDAE3AC7048F69C90FC52898220D369D30F13C0ED4FC1218EE7EF2E602172648E71D4D2CA10C0117F7B8D2D42D73547D19B8F4379D68ACD8B2419105044D2F542B3CB72A8E475962FB769C55275F54A01483A435DE815ADC7ECC65E06F0AF173292D9E79C58BAB29070B1FB97C263FF38533AA969E85B36A1FD10AC4F7C3F2F877DF9841E57735DC2B37A133A609170F9BF6B2973599E23BCB0E01AD906A997E52D75F308CFD22024A34D2F31B73521F31329C41144EFC5C6222A707AC4523F94DBB4B73455FB4BC69B79259D90BBE6E9BD85CA89A1989D200660E331D2843200131648F9044F84B5B03007AE2168135D8B6B42D3F945071BA9B02781AC5348A24C80BF670A1530D039CB37723CA04674F7F86C5B91AC4D896C185D15127C560CB17DA0B87FA3F92F552B6BD0C8E45EB80616372298288E15C3BFDFFE0D7041D948F247D4B14ADB2B4E947E1DE564F660F0E645201C77F3F8799397CDEE4B7AFF3FB8CD7B004682E03BF96FEC88E088B1B3AD78D37CA6218CE30A1BC4115E57E81E23AEC0B592F351B32F6BB2A7DCD367CC140787A424A700943A94C1C88EE70ED4541423AEA1733C50F02AAFFF5BECCB9B0E32231F2E9E3D433F62BC0C95C044FAD35B11DD4226882B947AD6E7666
```
</details>

Is this something that's expected to happen? While I'm not super familiar with CMS/PKCS7 yet, I'd be happy to help troubleshoot this however I can. Thanks!

**Comment by chenxiaolong** [comment]
I wonder if I'm using the API wrong. It seems that the issuer `Name` has multiple RDNs, but `RelativeDistinguishedName::try_from(issuer)` only looks at the first one:

https://github.com/indygreg/PyOxidizer/blob/66bcef6b9c1e1b780f4c67c98af91699871084c2/cryptographic-message-syntax/src/certificate.rs#L147-L158

**Comment by indygreg** [comment]
The fact this is erroring after ASN.1 parsing is good: that likely means the problem is in one of our higher-level helper APIs.

It seems you are using `RelativeDistinguishedName`. That class is kinda hacky: I'm not surprised it isn't working correctly. I would very much like to rip it out and use something like https://crates.io/crates/x509-parser instead. The reason I haven't done that yet is because all the ASN.1 is implemented with the `bcder` crate instead of `yasna`, which `x509-parser` uses. Use of `bcder` was probably a sub-optimal choice on my end. But when I started on this project I couldn't get `yasna` to work (maybe I wasn't doing things right) and `bcder` was the first crate I got to parse CMS BER. So here we are.

Maybe I should add a helper method to re-parse the X.509 certificates with the `x509-parser` crate. It should _just work_. And that would allow us to rip out a bunch of highly suspect code for dealing with certificates. It might introduce an extra crate dependency or two. But I'm not too worried about that since a) I'd like to port to `yasna` in a future release b) the dependency tree is already quite large due to `reqwest`.

Thank you for the bug report and the example demonstrating failure.

**Comment by indygreg** [comment]
(For the record, I just created the `cryptographic-message-syntax` label: so you didn't miss it when you filed this issue.)

**Comment by indygreg** [comment]
I was wrong about `x509-parser` using `yasna`. Anyway, that's relevant because it isn't trivial to convert between `Certificate` and that crate's version using `TryFrom` because https://docs.rs/x509-parser/0.9.2/x509_parser/certificate/struct.X509Certificate.html doesn't have `'static` lifetimes.

I think what you should do as a workaround is call `Certificate.as_der()` to get the DER bytes, feed those into `x509_parser::parse_x509_certificate()`, and use that type's APIs for examining the certificate.

I'll try to look into why our high-level RDN wrapper isn't working when I have more time.

**Comment by chenxiaolong** [comment]
Thanks for the info! I'll poke around `x509-parser` and see if there's something I can use in there.

My use case is rather obscure in that I'm trying to grab the common name and serial number from the CMS `SignerInfo`s without having access to any certificates. (I'm using those values to match against a list of rules to determine if a file should be resigned.)

By the way, I'm very happy this crate exists at all. I haven't found any other library that exposes the CMS internals aside from the openssl C API, which doesn't have a Rust wrapper for the CMS types/functions.

**Comment by chenxiaolong** [comment]
I was able to work around the issue with 3 methods:

1. Along the lines of your suggestion, encoding `signer.certificate_issuer_and_serial().0` (`Name`) as BER and then decoding it using x509-parser's `X509Name`.
2. Manually parsing the common name using the CMS crate's low-level API. (Doing what the high-level RDN wrapper does, but for each RDN in the sequence until the common name is found.)
3. Construct a new high-level RDN wrapper for each RDN in the sequence until the common name is found.

I created a minimal example with all 3 workarounds here: https://gist.github.com/chenxiaolong/66e7651a341aae760a63b2f3773d8b3f

```
❯ cargo run -- ../output.ko.sig
   Compiling cms_test v0.1.0 (/home/chenxiaolong/git/auto-pesign/files/cms_test)
    Finished dev [unoptimized + debuginfo] target(s) in 2.31s
     Running `target/debug/cms_test ../output.ko.sig`
CN (method 1): Ok("Fedora kernel signing key")
CN (method 2): Some("Fedora kernel signing key")
CN (method 3): Some("Fedora kernel signing key")
```

**Comment by indygreg** [comment]
I found a number of issues with the `Name` handling in this crate. One of the biggest was we were using a single RDN instead of an RDN for each component.

In the last few days, I also split out the X509 certificate handling code into its own `x509-certificate` crate, also part of the repository. As part of doing that, I flushed out the APIs and fixed a few bugs, like the aforementioned `Name` helpers.

I also addressed some other bugs in the CMS crate in the past few days as part of getting our signatures to pass Apple's code signature verification code, which uses its own CMS parser.

Please check out the new code and let me know if things are better!

**Comment by chenxiaolong** [comment]
Thank you! The new `Name::iter_common_name()` function works perfectly. Tested with: https://gist.github.com/chenxiaolong/6a0cb0a6531748affbe1fb0db2dd6ebb
