### ISSUE TITLE
cannot build in linux (ubuntu 20.04) the project created by pyoxydizer init-rust-project (v 0.13.2)

### ISSUE THREAD

**Issue by julienfr112** [indygreg/PyOxidizer#390]
`
$ pyoxidizer --version
PyOxidizer 0.13.2
commit: unknown
source: https://github.com/indygreg/PyOxidizer.git
pyembed crate location: version = "0.13.2"

$pyoxidizer init-rust-project rust_app
...
$cd rust_app/
$cargo build
   Compiling regex v1.4.6
   Compiling mailparse v0.13.4
   Compiling paste v0.1.18
   Compiling spdx v0.4.0
   Compiling tugger-licensing v0.2.0
   Compiling python-packaging v0.6.0
   Compiling python3-sys v0.5.2
error: failed to run custom build command for `pyembed v0.13.2`
running: "ar" "s" "/tmp/pyoxidizer-build-exe-packaging9p9CMg/libpythonXY.a"
  exit code: 0
  libpythonXY created
  error: error calling build(): Runtime(RuntimeError { code: "PYOXIDIZER", message: "writing packed resources", label: "build()" })

  --- stderr
  thread 'main' panicked at '`pyoxidizer run-build-script` failed', /home/julien/.cargo/registry/src/github.com-1ecc6299db9ec823/pyembed-0.13.2/build.rs:62:17
`

**Comment by indygreg** [comment]
I can reproduce this on the `main` branch. Thanks for the report.
