### ISSUE TITLE
Package metadata is inaccessible if the package name contains an underscore

### ISSUE THREAD

**Issue by bryan-koroleski-fivestars** [indygreg/PyOxidizer#394]
Currently, if you install a package with an underscore in its name, you will not be able to access its metadata through `importlib.metadata`. This issue occurs with both the `in-memory` and `filesystem-relative` resource locations. For example, here's what happens when you try to access `sentry_sdk`'s metadata:

```py3
Python 3.9.4 (default, Apr 14 2021, 22:52:01) [MSC v.1928 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib.metadata
>>> importlib.metadata.distribution("sentry_sdk")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "importlib.metadata", line 524, in distribution
  File "importlib.metadata", line 187, in from_name
importlib.metadata.PackageNotFoundError: sentry_sdk
```

However, accessing the metadata for `urllib3` works as expected:

```py3
>>> importlib.metadata.distribution("urllib3")
<OxidizedDistribution object at 0x00C69710>
```

After inspecting the file structure created with the `filesystem-relative` location, I've figured out that PyOxidizer is renaming `sentry_sdk-1.0.0.dist-info` to `sentry-sdk-1.0.0.dist-info`. This change renders the metadata unreadable by `importlib.metadata`, even if you try to pass the new name into `importlib.metadata.distribution`:

```py3
>>> importlib.metadata.distribution('sentry-sdk')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "importlib.metadata", line 524, in distribution
  File "importlib.metadata", line 187, in from_name
importlib.metadata.PackageNotFoundError: sentry-sdk
```

I managed to get things working with the `filesystem-relative` location by making this change:

```diff
diff --git a/python-packaging/src/resource.rs b/python-packaging/src/resource.rs
index eba58565..94f838ec 100644
--- a/python-packaging/src/resource.rs
+++ b/python-packaging/src/resource.rs
@@ -421,10 +421,10 @@ impl PythonPackageDistributionResource {
     pub fn resolve_path(&self, prefix: &str) -> PathBuf {
         let p = match self.location {
             PythonPackageDistributionResourceFlavor::DistInfo => {
-                format!("{}-{}.dist-info", self.package, self.version)
+                format!("{}-{}.dist-info", self.package.replace("-", "_"), self.version)
             }
             PythonPackageDistributionResourceFlavor::EggInfo => {
-                format!("{}-{}.egg-info", self.package, self.version)
+                format!("{}-{}.egg-info", self.package.replace("-", "_"), self.version)
             }
         };
```

I haven't managed to get this working for `in-memory` resources though and I'm not sure that this is the right place to change.

**Comment by indygreg** [comment]
I can confirm from Python's `importlib.metadata` module that normalizing `-` to `_` in package names is the correct thing to do.

I'll try to get a fix committed and in the next release. I also want to make sure the resources parser handles this correctly.

Thank you for the report!
