### ISSUE TITLE
Multiprocessing attempts to invoke `sys.executable` on Mac, enters infinite loop

### ISSUE THREAD

**Issue by layday** [indygreg/PyOxidizer#408]
On macOS with PyOxidizer 0.16.2, the resource tracker subprocess is not handled correctly; the multiprocessing arguments are passed to the CLI and with every attempt that is made to start the resource tracker, a new process is spawned.

See repro: https://github.com/layday/pyoxidizer-multiprocessing-tracker-crash (https://github.com/layday/pyoxidizer-multiprocessing-tracker-crash/runs/2696085714?check_suite_focus=true).

**Comment by layday** [comment]
Ah, I just noticed https://github.com/indygreg/PyOxidizer/issues/111.  I'll give 0.17 a try.

**Comment by indygreg** [comment]
Yes, I suspect this is fixed in 0.17 (which isn't yet released but can be downloaded from GitHub actions).

Please reopen if this is still a problem.
