### ISSUE TITLE
Unable to set a target triple for WiXInstaller instances

### ISSUE THREAD

**Issue by bryan-koroleski-fivestars** [indygreg/PyOxidizer#412]
I'm currently trying to package a 32-bit program and I'm using the `WiXInstaller` Starlark class because I need to customize the MSI file pretty heavily. After doing a little digging, I discovered that the target triple for `WiXInstaller` is always set to match the host OS instead of honoring the target triple specified on the command line. I've also found that unlike the `WiXMSIBuilder` class, you can't currently override the target triple on `WiXInstaller` instances.

I've experimented with exposing the target triple as a constructor argument to the Starlark class and that was pretty seamless. But, the `WiXMSIBuilder` class exposes this as a write-only attribute, so I'm thinking that might be a more consistent way to expose the target triple setting for both the `WiXBundleBuilder` and `WiXInstaller` classes. I could take a stab at making this change in the next few days but wanted to get your thoughts on it first.

**Comment by indygreg** [comment]
Using the target triple to sniff the default architecture feels a bit weird. And not providing a way to change the architecture is also limiting.

I'll hack up some changes to make this better.
