### ISSUE TITLE
Support configuration of index-url for pip installs

### ISSUE THREAD

**Issue by goedelsoup** [indygreg/PyOxidizer#42]
While a global index-url configuration will work fine in most cases, it would be beneficial to supply this value on specific builds as well.

**Comment by indygreg** [comment]
Good idea!

It's probably not worth the effort to duplicate every option that can be supplied to pip. So I think the way this should be implemented is as an `extra_args` option (or similar) that accepts an array of strings to pass to arguments to the invoked `pip` command. This is nearly infinitely extensible and should placate even the most discerning user's needs. It does allow people to shoot themselves in the foot by doing something unwanted. With great powers come great responsibility. This is a lesser evil than having to define dozens of options to control pip's various knobs.

**Comment by indygreg** [comment]
Support for this just landed and will be in the next release. You can build PyOxidizer from the Git repository if you want the feature immediately.
