### ISSUE TITLE
PyOxidizer on macOS requires at least macOS 11.0 SDK

### ISSUE THREAD

**Issue by messense** [indygreg/PyOxidizer#431]
`DeploymentTargetSettingName` only defined since macOS 11.0 SDK as you can see [here](https://github.com/phracker/MacOSX-SDKs/search?q=DeploymentTargetSettingName), ~~it's also not defined in SDKs from Xcode CommandLineTools even on macOS 11.0 and later.~~

https://github.com/indygreg/PyOxidizer/blob/5ce21160843ddb454bd561ef9c0181a86cc6f3a0/pyoxidizer/src/project_building.rs#L173-L177

This causes the `"unable to identify deployment target environment variable for macosx"` error when running `pyoxidizer build` as seen in #414

**Comment by indygreg** [comment]
This is a legitimate bug with the way we parse the SDK metadata. Thanks for reporting it.

However, PyOxidizer requires that you use an Apple SDK no older than the one used to build the Python distribution that PyOxidizer uses in its binaries. That is currently the 11.1 SDK. So run-time environments will need to have a macOS 11.1+ SDK installed for PyOxidizer to build binaries targeting macOS. The code you flagged is part of the validation ensuring this.
