### ISSUE TITLE
create unit tests

### ISSUE THREAD

**Issue by seanjensengrey** [indygreg/PyOxidizer#44]

**Comment by seanjensengrey** [comment]
Integration/test harness for https://github.com/indygreg/PyOxidizer/blob/main/pyoxidizer/src/pyrepackager/fsscan.rs

**Comment by indygreg** [comment]
I created some tests for the `fsscan` module. Since I don't think this issue is that actionable, I'm closing it.

In general, we need a lot more tests for PyOxidizer. I will happily accept pull requests that implement tests!
