### ISSUE TITLE
create ci/cd pipeline

### ISSUE THREAD

**Issue by seanjensengrey** [indygreg/PyOxidizer#45]
Run [clippy](https://github.com/rust-lang/rust-clippy)

**Comment by seanjensengrey** [comment]
Run [clippy](https://github.com/rust-lang/rust-clippy)

**Comment by indygreg** [comment]
I think the Twitter braintrust decided that Azure Pipelines is the preferred solution here.

Once we have CI in place, I'd like to address #24.

**Comment by indygreg** [comment]
I implemented basic CI support using Azure Pipelines in 75fcd239d9c3d7d60793d2f3aa1a60f9808eb210. It was the easiest cross-platform CI integration I've ever configured.
