### ISSUE TITLE
pytest compatibility with pyoxidizer

### ISSUE THREAD

**Issue by franzhaas** [indygreg/PyOxidizer#492]
I am using pytest with pyoxidizer single file executable succesfully after a minor change to pytest.

A pull request to incorporate the fix is currently under discussion, the majority apears to lean to the idea to change pyoxidizer to return [] None or a list of paths instead of throwing NotImplementedError.

https://github.com/pytest-dev/pytest/pull/9477

I am not convinced that this is a good idea, as i cant imagine a return value that is correct and helpfull.

Has anyone an idea what return value would be usefull?

**Comment by franzhaas** [comment]
this didnt go anywhere...

**Comment by alextremblay** [comment]
Can this be reopened here in pyoxidizer?

I agree with the maintainers of pytest. according to the spec, accessing dist.files should not raise an error when accessing an in-memory distribution, it should return None.

I would gladly submit a PR to fix this issue, but i have no idea where in the codebase this is implemented :(

**Comment by franzhaas** [comment]
I am not sure about this. While the spec says that there shall be none [] or a list of files, the wording implies that this refers to either no metadata (which is not true here) or no files in metadata (which is true but not helpful).

I believe that an exception, in this case, is the optimal solution.
