### ISSUE TITLE
Missing PyEval_SaveThread call after interpreter initialization?

### ISSUE THREAD

**Issue by mxk** [indygreg/PyOxidizer#500]
The docs for `MainPythonInterpreter::new()` state that the GIL is held when it returns. At first, I thought that this was a doc error, since the only `Python` instance is destroyed at the end of `MainPythonInterpreter::init()`. However, `PyGILState_Check()` does return 1 after `new()` returns, which means that the interpreter can only be used from the thread that initialized it.

Is there a reason for this or should there be a call to `PyEval_SaveThread()` at the end of `MainPythonInterpreter::init()`, similar to how `pyo3::prepare_freethreaded_python()` does it?

**Comment by mxk** [comment]
The project I'm currently working on only uses `MainPythonIntepreter` for initialization and multiprocessing dispatch, and does everything else through PyO3. I can't think of a reason for it to have the `gil` field. Here's a simplified version of my init code:

```rust
pub fn init() {
    static mut INTERP: MaybeUninit<MainPythonInterpreter> = MaybeUninit::uninit();
    static ONCE: Once = Once::new();
    ONCE.call_once(|| unsafe {
        INTERP.write(
            MainPythonInterpreter::new(embedded_config())
                .expect("failed to initialize Python interpreter"),
        );
        // https://github.com/indygreg/PyOxidizer/issues/500
        if pyo3::ffi::PyGILState_Check() != 0 {
            pyo3::ffi::PyEval_SaveThread();
        }
    });
    let interp = unsafe { INTERP.assume_init_mut() };
    if interp.is_multiprocessing() {
        std::process::exit(interp.run_multiprocessing().unwrap_or_else(|e| {
            Python::with_gil(|py| {
                e.print(py);
                1
            })
        }))
    }
}
```

This basically replaces `pyo3::prepare_freethreaded_python()`. It would be nice if PyO3 provided a way to hook into the `auto-initialize` feature, which would remove the need for explicit `init()` calls.

**Comment by indygreg** [comment]
I just pushed a handful of commits that refactor APIs on `MainPythonInterpreter` to better handle the GIL. And most importantly, `MainPythonInterpreter` now releases the GIL during initialization. Along the way, I think I fixed some corner cases that could cause crashes and made the overall state management of `MainPythonInterpreter` simpler by having it be agnostic about whether it is holding the GIL.

Please take a look and let me know if you think there's anything further to do here.
