### ISSUE TITLE
api requires passing in a `slog::Logger`

### ISSUE THREAD

**Issue by dvc94ch** [indygreg/PyOxidizer#510]
Seems kind of weird. Usually the `log` or `tracing` crates are used for logging and then the user configures a logger in their `main.rs`. Any particular reason why the logger is hardcoded (in the `apple-codesign` crate)?

**Comment by indygreg** [comment]
I adopted the `slog` crate a few years ago, as it seemed popular at the time. I now see that `log` and supplementary crates like `env_logger` are more in factor in the Rust ecosystem. So I'll switch to using those to make the API simpler.
