### ISSUE TITLE
after signing rcodesign reports errors when running verify

### ISSUE THREAD

**Issue by dvc94ch** [indygreg/PyOxidizer#512]
I'd expect that during signing with rcodesign, either an error is reported or verify succeeds. The errors I get are:
```
rcodesign verify helloworld.app/main
slot digest contains digest for slot not in signature: Resources (3) with digest 1d60f3357b22300fa3f153373553299fde00cc653d8c20f9327a604f1b11ec7d
slot digest contains digest for slot not in signature: Info (1) with digest 64d946930ad89c3335f1417dbee564d4c325615d08e5df5a721df7acab5ca68f
Error: problems reported during verification
```

**Comment by indygreg** [comment]
This looks like a legit logic bug in how digests and blobs are currently handled. Thanks for reporting it!

**Comment by indygreg** [comment]
Actually, it is a bug in the verifier. Some slots have digests but no corresponding blob entries. The `info` and `resources` slots are exactly the 2 slots that the code base knows about having this property.
