### ISSUE TITLE
The signature does not include a secure timestamp

### ISSUE THREAD

**Issue by inolen** [indygreg/PyOxidizer#522]
Hey Greg!

First off, thanks for the amazing work here. I've been trying to deal with signing / notarizing / stapling cross-compiled builds and this was such a relief to find.

I initially was using adhoc codesigning with ldid, but I've now setup a developer account to try and deal with notarizing / stapling (using https://github.com/LiamHaworth/notarization-helper) and am now using rcodesign for signing with an actual cert. 

My current command line for signing looks like:

```
codesign sign --binary-identifier <my_bundle_id> --code-signature-flags runtime --entitlements-xml-path <my_entitlements_path> --pfx-file <my_key_path> --pfx-password <my_password> <src_bin> <dst_bin>
```

With this, the notarization server is spitting back:

```{
  "status": "Invalid",
  "statusSummary": "Archive contains critical validation errors",
  "statusCode": 4000,
  ...
  "issues": [
    {
      "severity": "error",
      "code": "",
      ...
      "message": "The signature of the binary is invalid.",
      "docUrl": "",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": "",
      ...
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "",
      "architecture": "x86_64"
    },
  ]
}
```

Meanwhile, running `rcodesign verify <bin>` returns no errors.

Do you have any suggestions for debugging this with `rcodesign extract`? It seems most interesting to see how the timestamp is going missing, and once fixed, to see if it's still complaining about the signature.

**Comment by inolen** [comment]
As an update, I debugged this by hammering away at this until running `spctl --assess --type execute -vv myapp.app` stopped reporting errors.

In the end, the issue was that I wasn't filling out the full chain via `--pem-source`. Since I had a Developer ID Application cert, I was missing `--pem-source AppleIncRootCertificate.pem DeveloperIDG2CA.pem --` from my command line.

**Comment by indygreg** [comment]
I'm glad you were able to debug this on your own and get this working!

It's interesting that the notarization server was complaining about a missing timestamp: `rcodesign` will contact a timestamp server by default during the `sign` command. That may warrant investigation. Although it sounds like it was a false report on Apple's end?

If there's anything actionable here, it might be to automatically add CA certificates when the signing certificate is signed by a known Apple CA. That feels like a user-friendly and desired default behavior. I'll file an issue for that.

Please don't hesitate to file additional issues as you find rough edges with this tool!
