### ISSUE TITLE
pyoxidizer 0.20.0 runtime behavior change

### ISSUE THREAD

**Issue by chenrui333** [indygreg/PyOxidizer#523]
👋  it looks like pyoxidizer has some behavior change in the most release update.

Before I can run

```
$ pyoxidizer init-rust-project hello_world
$ cd hello_world
$ pyoxidizer build
```

But now `pyoxidizer build` does not do anything unless I append the `--verbose` flag.

kind of relates to https://github.com/Homebrew/homebrew-core/pull/96411

---

as mentioned by @cho-m

> Probably upstream issue/change due to https://github.com/indygreg/PyOxidizer/commit/6a1def475518c079683214ab9c06c6c330425db7

> .arg_required_else_help(true) is set for pyoxidizer build

**Comment by indygreg** [comment]
Thank you for the bug report! I've fixed this in `main`. Will hopefully get a release out the door in the next few days.
