### ISSUE TITLE
Entitlements signing question

### ISSUE THREAD

**Issue by inolen** [indygreg/PyOxidizer#527]
Hi Greg,

I ran into an issue tonight where I was attempting to use `--entitlements-xml-path` to add the `com.apple.security.cs.allow-jit` to my software. I _thought_ it was sufficient to pass this when signing the actual .app, but I finally realized my entitlements weren't working because I needed to add them to my binary, not the .app.

Is it expected that the entitlements would be added recursively to the binary when passing the .app as the input?

**Comment by indygreg** [comment]
I looked at the source code for this and I believe the entitlements XML should make its way through to the main executable within the bundle.

Could you please provide the exact command you are using and the output from its execution? There is more logging on the latest commit in the `main` branch. If you `cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main rcodesign` there should hopefully now be enough output to help debug whether the entitlements are making their way to the binary.

**Comment by inolen** [comment]
@indygreg mind sanity checking a rust newbie here. running 

```
$ cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main rcodesign
    Updating git repository `https://github.com/indygreg/PyOxidizer.git`
error: could not find `rcodesign` in https://github.com/indygreg/PyOxidizer.git?branch=main with version `*`
```
fails, but running 

```
cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main apple-codesign
```
succeeds in doing something. is the command you posted correct and i'm running some outdated tooling, or is that parameter supposed to be `apple-codesign` vs `rcodesign`.

**Comment by indygreg** [comment]
Sorry - my suggestion was wrong. The `cargo install` command you deduced is correct. (That's what I get for not testing this myself before posting my comment!)

**Comment by indygreg** [comment]
Another potential problem here is until literally seconds ago, `rcodesign` wouldn't write out DER encoded entitlements in the code signature. Apple's `codesign` would write out entitlements both in XML and in DER encoded form and we were only doing the former. As of commit 79d3b0684e14961a3a3bb6702302fd168b14bd9a the `main` branch now writes out both forms and should match the behavior of `codesign` as of macOS 12.

Please try this out and report back your experience!

**Comment by indygreg** [comment]
I fixed a ton of bugs related to bundle signing in the past few days. Could you please try to use the 0.11.0 release and report your results?

**Comment by indygreg** [comment]
The 0.13 release on 2022-04-10 contains a few bug fixes related to entitlements handling.

Could you please report your results with this version?

**Comment by indygreg** [comment]
Issue has been dormant. So assuming it is fixed. Please reopen or file a new issue if there is still a problem.
