### ISSUE TITLE
XAR error when signing package without output_path

### ISSUE THREAD

**Issue by magarcia** [indygreg/PyOxidizer#565]
When I try to sign a package without providing an `output_path`

```sh
rcodesign sign --p12-file ./signing-cert.p12 --p12-password-file ./passwd ./installer.pkg 
```

I got the following error.
```
registering signing key
automatically registered Apple CA certificate: Developer ID Certification Authority
automatically registered Apple CA certificate: Apple Root CA
using time-stamp protocol server http://timestamp.apple.com/ts01
automatically setting team ID from signing certificate: XXXXXX
signing ./installer.pkg in place
signing XAR pkg installer at ./installer.pkg to ./installer.pkg
performing empty RSA signature to calculate signature length
performing empty CMS signature to calculate data length
using time-stamp server http://timestamp.apple.com/ts01
generating new XAR table of contents XML
table of contents size: 13157
copying Bom to output XAR
Error: XAR error: I/O error: failed to fill whole buffer
```

Which doesn't happen if I provide an output path.
```sh
rcodesign sign --p12-file ./signing-cert.p12 --p12-password-file ./passwd ./installer.pkg ./installer-signed.pkg
```

This looks like an error on the moment to sign the package or at least on the documentation/help part, since its marking the `output_path` as optional.
`rcodesign sign [OPTIONS] <input_path> [--] [output_path]`

**Comment by indygreg** [comment]
It should be possible to sign a XAR in place. I suspect what's happening is we end up corrupting the file when modifying the file in place. Easiest workaround in code is to do what we do for DMGs and just copy the file before signing it. Not as efficient. But more robust.
