### ISSUE TITLE
How to install python dependencies from requirements.txt

### ISSUE THREAD

**Issue by ghost** [indygreg/PyOxidizer#577]
Hi @indygreg,

I followed your comments on this [thread](https://github.com/pantsbuild/pants/issues/7369) and having gone through the documentation. I don't see an easy way to install python dependencies required for the python code to work effectively with the embedded python intepreter. I even installed these packages locally but currently don't understand how to make pyoxidizer find and use them in pyo3. Any ideas and links will be greatly appreciated.

Cheers!

**Comment by Philistino** [comment]
Hi Nyanchor,

I am neither part of the development team nor an expert. I have been experimenting with pyoxidizer on one of my projects and I struggled through this a few days ago. The task became much easier once I found the page in the docs linked below. Candidly, this part of the documentation was not particularly easy to find quickly.

The easiest method that I have found in the documentation is to tell pyoxidizer to pip install the required package into the binary using the ```exe.add_python_resources(exe.pip_install(["PACKAGE_NAME_1", "PACKAGE_NAME_2", etc.]))``` in the make_exe function in your config file. One can also use a requirements.txt file. You can see how this is done in the link below.

You can also use this method to pip install a local repository if you want to turn your local python app repo into a binary.  However, this repo must be packaged in such a way that pip can install it (i.e., it includes a setup.py, etc.). You must then direct pyoxidizer to run a specific command to run your app when the binary is opened. This is done via the config portion of the make_exe function in the config file.  For example: ```config.run_command = "from myapp import main; main()"```. This is also discussed in the link below.

https://pyoxidizer.readthedocs.io/en/stable/pyoxidizer_packaging_python_files.html

I hope this helps!
