### ISSUE TITLE
cargo install fails, because old rustc used

### ISSUE THREAD

**Issue by nnovikov** [indygreg/PyOxidizer#580]
pyoxidizer use old rustc, some dependency can't build:
    package `handlebars v4.3.0` cannot be built because it requires rustc 1.57 or newer, while the currently active rustc version is 1.56.1

**Comment by indygreg** [comment]
Assuming this is a `cargo install` from outside a Git repository checkout, try `cargo install --frozen`. Or try an install of the source checkout from the tag you want to install, as it should use the `Cargo.lock` file in the repo automatically.

I'm pretty sure `cargo install` from crates.io only respects the version constraints in `Cargo.toml`. And if a crate dropped support for old Rust without incurring a major version bump, `cargo` will attempt to use the newer package. [Semantic] versioning is hard.
