### ISSUE TITLE
[apple-codesign] Use new REST API for notarization

### ISSUE THREAD

**Issue by roblabla** [indygreg/PyOxidizer#591]
Heyo,

At WWDC22, Apple announced that they were releasing a new REST API for notarization. I believe this would allow getting rid of the dependency on Apple Transporter. It supports submitting a new package to the notarization service, and getting the submission status and logs.

- Documentation: https://developer.apple.com/documentation/notaryapi/submit_software
- WWDC Video: https://developer.apple.com/videos/play/wwdc2022/10109/

**Comment by indygreg** [comment]
I saw this last week as well. We should implement support for the REST API (which appears to essentially by the formerly undocumented API used by `notarytool`) and delete the existing notarization code using Transporter and some undocumented APIs for polling notarization submissions.
