### ISSUE TITLE
`import ctypes` fails on Windows

### ISSUE THREAD

**Issue by indygreg** [indygreg/PyOxidizer#61]
`import ctypes` currently fails on Windows:

```
>>> import ctypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ctypes", line 439, in <module>
  File "ctypes", line 356, in __init__
OSError: [WinError 126] The specified module could not be found
```

I thought I fixed `ctypes` issues by patching CPython via indygreg/python-build-standalone. But I guess I forgot to verify on Windows.

For context, line 439 is `pythonapi = PyDLL(_sys.executable)` and 356 is `self._handle = _dlopen(self._name, mode)`. `_dlopen` is aliased to `LoadLibrary`, so basically this is failing on a `LoadLibrary(self_exe)`.

All of this to set a `ctypes.pythonapi` attribute, which is part of the documented public API for `ctypes` but doesn't appear to be used by CPython itself. I wonder what in the wild is using it...

(This issue derived from a reported problem with `click` in #25.)

**Comment by hammerheadlemon** [comment]
I am seeing this bug at runtime too having successfully built on Windows 10.

**Comment by indygreg** [comment]
Turns out that the Python builds were correct, it was PyOxidizer that was populating `sys.executable` incorrectly and throwing off `ctypes`.

This should now be fixed on the `main` branch.
