### ISSUE TITLE
Loading binary file from inside packaged application

### ISSUE THREAD

**Issue by callicles** [indygreg/PyOxidizer#7]
Hi!

Thanks for this, this is pretty amazing work.

I am trying to package a CLI app that is using `requests` and `certifi` as such, the certificates are bundled inside the `certifi` package as a `pem` file.

The way they load the package is through `__file__` global variable which do not seem to be set when running the interpreter.

It looks like this is linked to [ResourceReader](https://docs.python.org/3.7/library/importlib.html#importlib.abc.ResourceReader) problem.

I am willing to contribute but I need some direction to fix this.

Thank you!

**Comment by indygreg** [comment]
So, any package relying on `__file__` and assuming `__file__` is an actual filesystem path will not work with pure memory importing.

Going forward, Python packages should attempt to use the `ResourceReader` interface for loading these types of resources. You should file an issue against `requests`/`certifi` to use this interface if available and to fall back to `__file__` as necessary. 

https://discuss.python.org/t/standalone-app-deployment-story/920/19 has some useful discussion about this problem.

However, we do not yet support `ResourceReader` in PyOxidizer. That feature definitely needs to be implemented. I just haven't gotten around to it yet. It will require teaching the custom importing mechanism to expose an object implementing the `ResourceReader` interface. And we'll need to embed resource files in the binary somehow. Probably the biggest hurdle here is how to "index" the resources. The `ResourceReader` interface allows filesystem implementation details to bleed through. Read https://bugs.python.org/issue36128 and https://gitlab.com/python-devs/importlib_resources/issues/58 for more.

We can also work around this by supporting loading modules from the filesystem, like any existing Python application. We don't yet expose good controls in PyOxidizer's TOML config files to enable this.

Another option which I haven't investigated yet is perhaps teaching Python's `open()` to work with in-memory *paths*. I'm not even sure this is feasible without gruesome hacks to the compiled Python interpreter. This path may culminate in a PEP / Python feature to support abstract filesystems for I/O. And I have doubts the Python community would want to tackle such a problem given better solutions are available.

**Comment by indygreg** [comment]
PyOxidizer now supports the `ResourceReader` interface. There are still some rough edges around the naming and filtering of resources that are packaged. But it does work.

Also, PyOxidizer supports enabling the traditional filesystem importer. So worst case you can fall back to that if packages don't support `ResourceReader` or insist on the existence of `__file__`.

The documentation at https://pyoxidizer.readthedocs.io/en/latest/packaging.html#packaging-additional-files and https://pyoxidizer.readthedocs.io/en/latest/packaging_pitfalls.html#reliance-on-file covers this matter.

I'm going to call this issue closed. Please file new ones for rough edges around the packaging of resources data. I know there are a handful of things broken with it. What I don't know is which ones are most important for people in the wild. So please tell me!
