### ISSUE TITLE
setup-py-install packaging failure with django

### ISSUE THREAD

**Issue by ipmb** [indygreg/PyOxidizer#70]
I have a local copy of [django](https://github.com/django/django) that I am trying to use in pyoxidizer with:

```toml
[[packaging_rule]]
type = "setup-py-install"
package_path = "../django"
```

When running the build, I get the following error:

```
processing packaging rule: SetupPyInstall(PackagingSetupPyInstall { path: "../django", optimize_level: 0, include_source: true, install_location: Embedded })
installing modified distutils to /tmp/pyoxidizer-setup-py-install.1sQDxAQMhvKG/packages
modifying distutils/_msvccompiler.py for oxidation
modifying distutils/command/build_ext.py for oxidation
modifying distutils/unixccompiler.py for oxidation
python setup.py installing to /tmp/pyoxidizer-setup-py-install.1sQDxAQMhvKG/install
running install
Checking .pth file support in /tmp/pyoxidizer-setup-py-install.1sQDxAQMhvKG/install/lib/python3.7/site-packages/
/home/ubuntu/projects/pyox_demo/pyox/build/target/x86_64-unknown-linux-gnu/debug/pyoxidizer/python.d6b80a9723c1/python/install/bin/python3.7 -E -c pass
TEST FAILED: /tmp/pyoxidizer-setup-py-install.1sQDxAQMhvKG/install/lib/python3.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /tmp/pyoxidizer-setup-py-install.1sQDxAQMhvKG/install/lib/python3.7/site-packages/

and your PYTHONPATH environment variable currently contains:

    '/tmp/pyoxidizer-setup-py-install.1sQDxAQMhvKG/packages'

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations


Please make the appropriate changes for your system and try again.
thread 'main' panicked at 'error running setup.py', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/pyoxidizer-0.2.0/src/pyrepackager/packaging_rule.rs:1061:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Running `python setup.py install` from within that directory works as expected.

I'm seeing this error in both MacOS and Linux using pyoxidizer 0.2.0.

**Comment by indygreg** [comment]
OK, this is a previously-unknown issue!

Django's `setup.py` appears to be testing for `.pth` file support as part of building and it insists that whatever file it is using to write the `.pth` to is on `PYTHONPATH`. Why it is doing this, I'm not sure.

We might be able to work around this by setting `PYTHONPATH` when invoking `setup.py`. If so, this may be an easy bug...

But if Django insists on using `.pth` files, we'll run into trouble later, as PyOxidizer doesn't recognize `.pth` files.

**Comment by ipmb** [comment]
It looks like this is standard setuptools behavior, see https://github.com/pypa/setuptools/blob/46be0276c7a3b95240ce36055d5ce73ab455e756/setuptools/command/easy_install.py#L537-L594

Could you point me to the part of Django's setup.py that might be triggering this?

**Comment by indygreg** [comment]
Oh, it does look like standard setuptools behavior! This is the first report of this failure and I assumed it was Django specific because large projects like Django tend to do unconventional things in `setup.py` scripts. I was wrong, apparently.

**Comment by indygreg** [comment]
With the patches I just pushed, I was able to build an application installing Django via a `setup-py-install` rule.

I'm not sure if Django actually works in a self-contained executable. If it doesn't, that would be a new issue to be filed, as this issue is about getting `setup-py-install` working with `setuptools`.
