### ISSUE TITLE
virtualenv package_rule doesn't work in Windows

### ISSUE THREAD

**Issue by matthewgdv** [indygreg/PyOxidizer#83]
It looks like PyOxidizer looks for virtualenv packages in .\Lib\python3.7\site-packages even on Windows, where the site-packages are actually located at .\Lib\site-packages (see https://docs.python.org/3/library/venv.html).

Should hopefully be an easy fix?

Cheers for this project, it's already looking pretty good. Can't wait to see what it looks like once it's matured a bit more :)

**Comment by indygreg** [comment]
I thought we handled the `site-packages` path correctly on Windows. I guess we missed a spot...
