### ISSUE TITLE
Unable to update https://github.com/indygreg/PyOxidizer.git?rev=6051a3a6e8cc743be40c8255ab3fe55bea45a7b6

### ISSUE THREAD

**Issue by svenstaro** [indygreg/PyOxidizer#85]
I build release 0.2.0 like this `cargo build --locked --release` and then use the `pyoxidizer` binary. I then follow the basic guide:

```
pyoxidizer init lol
cd lol
pyoxidizer build
```

then it does a lot of things and in the end:

```
    Updating crates.io index
    Updating git repository `https://github.com/indygreg/PyOxidizer.git`
       Fetch [=========>                                             ]  19.07%                                      
error: failed to load source for a dependency on `cpython`

Caused by:
  Unable to update https://github.com/indygreg/PyOxidizer.git?rev=6051a3a6e8cc743be40c8255ab3fe55bea45a7b6

Caused by:
  revspec '6051a3a6e8cc743be40c8255ab3fe55bea45a7b6' not found; class=Reference (4); code=NotFound (-3)
```

Current master appears to work. So maybe just a release would be helpful?

**Comment by indygreg** [comment]
Does `6051a3a6e8cc743be40c8255ab3fe55bea45a7b6` exist in any files in the `lol` directory you created? I'm really curious where this hash is coming from. I don't think it corresponds to a Git commit in PyOxidizer...

**Comment by indygreg** [comment]
I need more information in order to figure out what the problem is...

**Comment by svenstaro** [comment]
Closing as I can't reproduce myself.
