### ISSUE TITLE
Only one of `files` or `glob_files` attribute should be required in "filter-include" packaging rule 

### ISSUE THREAD

**Issue by regisb** [indygreg/PyOxidizer#88]
If I wanted to include just one requirements file, I would write:

```
[[packaging_rule]]
type = "filter-include"
files = ["allow-modules"]
```

However, this configuration fails with the following error:

```
$ RUST_BACKTRACE=1 PYOXIDIZER_WRITE_MODULES_DIR=/tmp/my-modules pyoxidizer build --target x86_64-unknown-linux-gnu
error: err reading config /home/user/pyoxidizer.toml: missing field `glob_files` for key `packaging_rule`
```

A similar error occurs when I define the `glob_files` attribute but not `files`. As a consequence, I need to write the following redundant rules:

```
files = ["allow-modules"]
glob_files = ["allow-modules"]
```

I'm using pyoxidizer 0.2.0 on Linux.

PS: Congratulations on building PyOxidizer! I'm eager to use it to produce MacOS builds of my python project without having to rely on Travis CI.

**Comment by indygreg** [comment]
This is a silly bug! Thank you for the report.

**Comment by regisb** [comment]
Awesome, keep up the good work! :+1:
